### ISSUE TITLE
file extension for uncompressed BCF files

### ISSUE THREAD

**Issue by atks** [samtools/hts-specs#114]
Is there a recommendation for naming uncompressed BCF files?  e.g. *.ubcf

**Comment by pd3** [comment]
No, they are named the same, `*.bcf`. If unsure what file type it is, one use `htsfile` or peek inside using `less`.

**Comment by atks** [comment]
I was thinking of the naming convention as a way to automatically figure what output to set when writing a file without setting additional options.  Right now we have:

vcf - uncompressed vcf
vcf.gz - compresses vcf
bcf - compressed bcf

that's why I was wondering if it might be a useful thing to have a name to differentiate compressed and uncompressed bcf.

**Comment by atks** [comment]
I'm now of the opinion that we should stick to bcf and that it is better to specify the compression level or lack of separately as there are many levels to choose from (i.e. 0-9 bgzf levels and uncompressed) and that uncompressed bcf is just a special case.  closing this.
