### ISSUE TITLE
Two question about the Sequence Alignment/Map Format Specification

### ISSUE THREAD

**Issue by maoyibo** [samtools/hts-specs#116]
Hello!
I have two question about the Sequence Alignment/Map Format Specification (file:SAMv1.tex)    

1. In the "1.2 Terminologies and Concepts",you define "Template" as "A DNA/RNA sequence part of which is sequenced on a sequencing machine or assembled from raw sequences."  
    I am confused about this concept.Does template just the same as the explanation in the wikipedia "a strand of DNA which sets the genetic sequence of new strands.a strand of RNA which translates genes into proteins", stand for the template you want to research and mapped or aligned to the reference sequence. The template'sequence could be sequenced on a sequencing machine or assembled from raw sequences.   
    I find somebody explain this "Template" as "The reference sequence and the alignment sequence aligned to it together constitute the Template".  
    which explanation is correct?  
2. In the "0-based coordinate system","the region between the 3rd and the 7th bases inclusive is [2, 7)". The region contain 3th,7th,and bases between them,but with out 2th base.I think the interval should be (2,7].  

I hope I have expressed my question correctly. 
Looking forward to your reply in time.

**Comment by yfarjoun** [comment]
1. Yes. Same as wikipedia. in particular, it has nothing to do with the
reference.
2. I think that this is an language issue, the terms "first", "second",
"third" etc, are _not_ subject to the 0-based counting. Eg: If the bases
are ACGT, the 1st base is A, the second C etc. Thus the region between the
C (2nd) and T (4th) inclusive, in the 0-based system is [1,4).

I hope this helps.

Yossi.

**Comment by maoyibo** [comment]
Thank you Yossi ! 
Your reply completely answered my question, I have no doubt now.
