### ISSUE TITLE
CRAM ref id -2

### ISSUE THREAD

**Issue by jkbonfield** [samtools/hts-specs#118]
Reported by Xiaofeng Liu, added here as reminder to fix in new year.

Ref id -2 (multiple references) is explained in section 7, but not section 8.5 (page 10 of PDF).  Double check with Vadim, but I suspect this was just an accident where we forgot to update both structures when we added the RI field (for CRAM v2? it's been like it since then at least).

**Comment by vadimzalunin** [comment]
@jkbonfield yes, seems like we just missed that one.

**Comment by jmthibault79** [comment]
#372 resolves this.
