### ISSUE TITLE
[CRAM] Default values for compression header preservation map

### ISSUE THREAD

**Issue by jkbonfield** [samtools/hts-specs#120]
I've just noticed that the C CRAM implementation doesn't normally set RR (reference required), unless a referenceless cram is produce (eg scramble -x).  Prior to RR being added we always needed a reference, but now we can say otherwise.

The logical default value therefore is 1; we need a reference unless explicitly told otherwise.   However no default value is listed.

I think we could have the following defaults, or perhaps just state that all the bools default to true if not given?

RN: 1
AP: 1
RR: 1
SM <no default, or pick the one we nearly always use?>
TD: <none>

**Comment by vadimzalunin** [comment]
Checked with java, htsjdk.samtools.cram.structure.CompressionHeader.referenceRequired is always true(RR=1) and it has no effect whatsoever. 
I agree, default values should be explicitly described otherwise it is impossible to rely on RR optimization.

**Comment by cmnbroad** [comment]
@jkbonfield For the booleans, I think default to true makes sense. Seems like TD and SM can remain optional though ?

If we're in agreement, I'll make a PR to tighten up the language in this ("Preservation Map") section of the spec. I always interpreted it to mean that these must all be present in the map; it wasn't until I saw this ticket that I realized that it doesn't **_actually_** say that, which is why the defaults need to be specified.

**Comment by cmnbroad** [comment]
Actually, the more I think about it, the more it seems like SM should be required, or at least the spec should state the circumstances under which it can be missing (I'm not sure what the possibilities are - no read features, or maybe RR=false ?).

**Comment by jkbonfield** [comment]
The reason they're not required is not all of them existing in previous versions of CRAM.  So code that supports multiple versions realistically has to cope with the lack of a value being there.  However we could make them mandatory for a specific version, and SM was in 1.1 even. (I think it appeared between 1.0 and 1.1?).  Infact all bar RR were in 1.1, so this reasoning is pretty flimsy.  No one cares about CRAM pre 2.0 and even that is very hard to find.

RR appeared in 3.0.  It was added as a hint to decoders that this data is storing data as-is, e.g. because it's unmapped but potentially still having SQ headers.  I see it's rather ambiguous as to whether RR should be 1 or 0 if the data uses internal embedded references and no external ones.  With hindsight it probably should have been tri-state.  I'd have to experiment to work out how htslib and htsjdk work in this situation, but I suspect it should be 1 for this case.  That needs documenting.

TD being absent is equivalent to it being set to blank (no aux tags present), so that's an easy one to cope with.

It's a good point about storing data verbatim; if we have no substitutions then SM is irrelevant.  It's tiny though so requiring it even when it's not needed is hardly bloat unless for some reason we're trapped into needing a lot of small containers.  Perhaps they should all be listed as mandatory except for TD and RR, and RR mandatory from 3.0 onwards.

**Comment by cmnbroad** [comment]
I guess I've now come around full circle to your original proposal. The spec doesn't currently say any of these are required, and the use of the map reinforces that they're optional. Changing the spec now to say they're required would be a file format change. I'd say lets just update the spec to be explicit that they're all optional, and that the booleans default to true if not present.

**Comment by jkbonfield** [comment]
Agreed, although we should give a default for the SM field unless we decide it's mandatory.

My own code starts with

A: CGTN
C: AGTN
G: ACTN
T: ACGN
N: ACGT

I *think* that equates to 0x1b 1b 1b 1b 1b. (00 01 10 11 for each).  I always create it though.  I've not tested deliberately avoiding writing it to see how it impacts our implementations.
