### ISSUE TITLE
VCF QUAL Score Ambiguity

### ISSUE THREAD

**Issue by pishotta** [samtools/hts-specs#122]
Dear Keepers of the Holy Writ,<p>I have encountered different and inconsistent interpretations of the VCF QUAL Score that can have some nasty consequences when used for filtering.  The VCF specs should provide the definitive answer, so I seek help here.  The problem relates to the calculation of the QUAL score for a non-variant locus.<P>The VCF 4.2 Spec defines QUAL as the "<b>Phred-scaled quality score for the assertion made in ALT. i.e. −10log10 prob(call in ALT is wrong). If ALT is ‘.’ (no variant) then this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10 prob(no variant). If unknown, the missing value should be specified.</b>" The 4.1 Spec also contained the statement: "<b>High QUAL scores indicate high confidence calls.</b>"<p>This seems clear to me,  Whether variant or non-variant, the <b>higher</b> the QUAL score, the <b>better</b> the call.  Just what I want for filtering all calls uniformly.  Problem is:  Not every generator of VCF files interprets and reports QUAL scores that way. For instance, the accepted explanation on the <a href="http://gatkforums.broadinstitute.org/gatk/discussion/1268/what-is-a-vcf-and-how-should-i-interpret-it">GATK Forum</a> is that QUAL is: "The Phred-scaled probability that a REF/ALT polymorphism exists at this site given sequencing data.</b>"  By this interpretation however, a highly confident call at a non-variant locus would get a <b>lower</b> QUAL score indicating the <b>lesser</b> probability of a variant.  So in the case of variant calls: the higher the QUAL score the better; and in the case of non-variant calls: the lower the QUAL score the better -- an inversion seemingly at odds with VCF specifications. I know the variant caller freebayes behaves this way, as (I believe) does bcftools when processing mpileup output.  Maybe this is correct, but it really screws up the direct utility of QUAL as a filter when considering all calls and not simply hunting for highly probable variants (e.g., producing high-quality datasets for case-control association studies). There are   ways to ameliorate this problem, but they are programmatically sub-optimal and convoluted.  So, as the published VCF Specs should be the ultimate authority in this matter, I ask:  Which is right?<p><ol><li>QUAL is a consistent measure of the correctness of the accompanying ALT field in the call record (ALT = "." being a call for the monomorphic reference allele specified in REF); or, </li><li>QUAL is always a measure of the likelihood that the locus is a polymorphic variant?</li></ol><p>Please.  The difference is critical, but I would not want to take anyone to task over not following the VCF specs if it is I who misinterprets them.  Anyway, "Enquiring minds want to know."<p>-- Fred P.

**Comment by lh3** [comment]
The spec is precise. GATK in fact implements essentially the same QUAL. The sentence you quoted from the forum is ambiguous. Ignore that.

**Comment by pishotta** [comment]
Thanks, but you didn’t answer my specific question.  Which is correct?

**Comment by lh3** [comment]
Neither of your interpretations is precise, so I did not answer to avoid further confusion. Just follow the spec. If you have to choose one, 1 is closer, but not exact.

**Comment by pishotta** [comment]
“Following the spec” is the problem.  I’m dealing with someone who believes he is following the spec by choosing option 2.  Please don’t just close the issue without providing some clarification.   That only increases the confusion.  This is a major issue.

**Comment by d-cameron** [comment]
The only issue I see with the spec is that it requires a single QUAL score for all ALT alleles thus for sites with multiple alternate alleles with different QUALs. Although the spec does define what the single QUAL score for the site should be, your approach of filtering by site QUAL will likely result in filtering of high-confidence alleles co-occurring with low confidence ones.
