### ISSUE TITLE
QUAL description references an ALT option that is not described

### ISSUE THREAD

**Issue by dotdotdotpaul** [samtools/hts-specs#126]
Just noticed this, dating back to v4.1, v4.2 and still present in v4.3 of the VCF spec:

The description of the QUAL field makes reference in section 1.4.1:

> If ALT is ‘.’ (no variant) then...

Problem is, the immediately preceding section, describing what can be in the ALT column makes no reference to "." as a valid entry.  In 4.1, the ALT column states:

> Options are base Strings made up of the bases A,C,G,T,N, (case insensitive) or an angle-bracketed
> ID String (“<ID>”) or a breakend replacement string as described in the section on breakends.

4.2 expanded this to include *:

> Options are base Strings made up of the bases A,C,G,T,N,*, (case insensitive) or an angle-bracketed
> ID String (“<ID>”) or a breakend replacement string as described in the section on breakends. The ‘*’ allele is reserved to indicate that the allele is missing due to a upstream deletion.

In neither does it state that "." is a valid entry, or expand on what it means.

If a "." is valid, and means, based on the QUAL description, "no variant" it should be noted as a possible value for ALT, and not inferred from the reading of the subsequent section.

In the meantime, can confirm for me:  if I receive a REF of 'A' and an ALT of '.' is that the same as having an ALT of 'A'?

...Paul

**Comment by dmyersturnbull** [comment]
Perhaps you should post a link to the specification you're referencing.
I've been following https://samtools.github.io/hts-specs/VCFv4.3.pdf, which says that "." is a valid ALT field in sections 1.6 and 1.6.1#5:

In 1.6:
> In all cases, missing values are specified with a dot (‘.’)

In 1.6.1#5:
>  If there are no alternative alleles, then the missing value should be used.

(I'll skip your question because I'm not on the Samtools/HTS team.)

**Comment by dotdotdotpaul** [comment]
I think you mean section 1.4.1 (there's no section 1.6).  I guess that still implies the ALT is effectively the same as the REF.  I guess I just prefer that all valid values are enumerated in the section they are defined.  Thanks

...Paul

**Comment by dmyersturnbull** [comment]
There is a section 1.6 in the specification I linked:

> 1.6 Data lines
> All data lines are tab-delimited with no tab character at the end of the line. The last data line should end with a line separator. In all cases, missing values are specified with a dot (‘.’).

That's why I suggested that you give a link to the spec you're referencing; I think they're different. I agree that it isn't the most clear.

**Comment by dotdotdotpaul** [comment]
I did:  "Just noticed this, dating back to v4.1, v4.2 and still present in v4.3 of the VCF spec:"  :)

I didn't notice that section changed by two minor numbers between 4.2 and 4.3, since the numbering hadn't changed between 4.1 and 4.2.  I'm still not clear on what it actually *means*, and I still prefer each section detailing the valid values for that section (as an engineer, better to be redundant and completely unambiguous)

Thanks for pointing out what I missed, regardless (though I still need to figure out what it means for a variant to "have no variant"...  :)

...Paul

**Comment by pd3** [comment]
VCF records can represent both polymorphic and monomorphic loci. Variant sites have ALT!=".", non-variant sites have ALT=".". Does this answer your question?

**Comment by dotdotdotpaul** [comment]
It might answer my question -- I'm actually not bioinformatics-oriented, I'm a software engineer.  :)

My "layman's understanding" is that the ALT represents the bases that were found in the sequence instead of the expected bases, represented by the REF.  So, A-G is a missense, A-AT is an inserted T, AT-A is a deleted T, etc. (using hyphens in place of tabs for legibility)  I understand if the ALT is comma-separated, it means multiple variants were found at the same location (ie. A-AT,G means both an insert and missense were found).  Just not sure what's intended by "A-."  Is it the same as saying "A-A" (ie. what was expected was found)?  Why not just say "A-A"?  If REF and ALT are identical, it's a "non-variant", is it not? 

Or is there a notable difference between a line where REF = ALT and a line where ALT = "." ?

...Paul

**Comment by dpryan79** [comment]
"A-." would either be "A-A" or "A-'we have no idea or lack sufficient information to make a guess'". Biologically speaking, "A-A" would be contradictory and one would ever write it.
