### ISSUE TITLE
Clarify BCF header format

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#138]
VCFv4.3 §6.2 says

> The BCF2 header begins with the “BCF2 magic” 5 bytes that encode `BCFXY` where X and Y are bytes indicating the major number (currently 2) and the minor number (currently 2). This magic can be used to quickly examine the file to determine that it’s a BCF2 file. Immediately following the BCF2 magic is the standard VCF header lines in text format, beginning with `##fileformat=VCFvX.Y`.

However BCFv2_qref and the htslib implementation have a 32-bit length before the header text:

| Field | Description | Type | Value |
| --- | --- | --- | --- |
| magic | BCF2 magic string | char[5] | BCF\2\1 |
| ￼￼￼l_text | Length of the header text, including any NULL padding | uint32_t | ￼￼￼ |
| text | NULL-terminated plain VCF header text | char[l_text] |  |

The main VCF/BCF spec should describe the BCF header length and text more completely.

**Comment by jmarshall** [comment]
See also samtools/htslib#373, which shows htslib's confusion as to whether `l_text` is supposed to be signed or unsigned.

**Comment by zhanxw** [comment]
Thanks for opening this issue, @jmarshall. 

Please change the text in the specification: "Immediately following the BCF2 magic is the standard VCF header lines in text format..." needs to change to "Immediately following the BCF2 magic is **the length of VCF header lines** and the standard VCF header lines in text format".

**Comment by jmarshall** [comment]
It needs a bit more than that; see https://github.com/samtools/hts-specs/issues/236#issuecomment-423999865.
