### ISSUE TITLE
Describe @HD's GO field

### ISSUE THREAD

**Issue by keiranmraine** [samtools/hts-specs#15]
Could 'collated' be added as a valid sort order for reads?  In many cases it isn't important to fully sort by name only bring pairs together and it would be useful if this was easy to detect from the header.

**Comment by mdshw5** [comment]
Could someone elaborate on what exactly GO stands for?

**Comment by jmarshall** [comment]
From the email message linked above:

> [e.g.] `@HD GO:query`, which is accepted by both samtools and Picard, but I don't think either of them do anything in particular with it.  This was described in earlier versions of the SAM/BAM spec as:
>
>   `GO`    Group order (full sorting is not imposed in a group). Valid values are: none, query or reference.

It's a slight misnomer.  It's really _grouped-by_, akin to the SQL construct.  The spec change mentioned is still "upcoming"...

**Comment by mdshw5** [comment]
Ah, thanks for clicking the link for me :). I hope to see this in the spec at some point, since I try to keep my work as close to the spec as possible.
