### ISSUE TITLE
Current spec is overly restrictive regarding ALT field

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#150]
The current spec requires that the alleles in the ALT field be _called_ in at-least one of the genotypes. 

from the spec (all versions that I could find, §1.6.1.5 in v4.3)
>    ALT - alternate base(s): Comma separated list of alternate non-reference alleles called on **at least one of the samples**.

(My emphasis)

This is, in my view, too restrictive, Furthermore, the restriction seems not to have been followed by some big projects (like [1000G](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz), and [EXaC](ftp://ftp.broadinstitute.org/pub/ExAC_release/release0.3.1/ExAC.r0.3.1.sites.vep.vcf.gz) as they both released "sites-only" vcfs.

Does anyone know/remember why the restriction was put in, or have an understanding of what it provides?

As it stands, the following three use-cases are not legal VCFs (according to my strict reading of the spec) and yet we use them all the time:

1. Sites-only vcfs, with no genotypes (for example those released by 1000G or EXaC to disseminate variant information without genotypes)
1. gVCF produced by GATK (and other callers) that have symbolic alleles that are not actually called in any of the genotypes.
1. VariantContexts that show reference confidence of monomorphic sites. This is becoming especially important (for clinical applications) since in order to show that a site is monomorphic one may wish to present what evidence to the contrary there is (and yet still emit a 0/0 call). 

----

I suggest:
- to remove the restrictive language from v4.3; and 
- to retroactively make the historic releases of data "valid" by updating the old versions as well.

**Comment by droazen** [comment]
This is a good example of why specs should be written as formal grammars from which parsers can be directly generated, instead of in words and sentences :) Let's try to get this on the agenda for the June 3rd file formats meeting.

**Comment by pd3** [comment]
@yfarjoun +1

**Comment by eitanbanks** [comment]
+1

**Comment by jmarshall** [comment]
:+1: from @richarddurbin in our group meeting today.

**Comment by jmarshall** [comment]
Fixed by #152.
