### ISSUE TITLE
Incorrect use of new-lines in .tex docs makes reviewing changes difficult

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#153]
Since folks put paragraphs in a single line, or arbitrarily break lines, while github looks at line-by-line changes.

I would like to propose a no-op change to the PDFs by restructuring all the .tex files to have a sentence per-line.

**Comment by jmarshall** [comment]
IMHO this is up to the respective editors of the various specifications.

Me, I would not support bulk changes as proposed, as they are make-work that noone really has time for and looking past them in the history is made more difficult.

The various spec editors should be cognisant of the need to make for comprehensible diffs, and do so in the parts of the text that they update.  This might mean 1 line = 1 sentence as proposed (as in [README.md](https://github.com/samtools/hts-specs/blob/master/README.md) for instance; for vim users, `set linebreak` is handy here), though even that has the downside that diffs become very wide (e.g. in _FileMerge.app_) and hence unreadable that way.
