### ISSUE TITLE
AD, ADF, ADR in VCF specification

### ISSUE THREAD

**Issue by danielmoney** [samtools/hts-specs#154]
The order of the depths for these fields is not defined in the VCF specification.  As far as I can see the only logical order is reference allele followed by the alt alleles in the order given but it would be useful to make this explicit for the avoidance of doubt (which has just occurred when discussing my software - which uses these fields - with a user).

**Comment by yfarjoun** [comment]
:+1:

Perhaps that should be mentioned in the section that talks in general about
the R and A Number option...something like:


   -

   If the field has one value per alternate allele then this value should
   be ‘A’. --->>
   -

      If the field has one value per alternate allele then this value
      should be ‘A’. The order of the values corresponds to the order of the
      alleles
      - If the field has one value for each possible allele (including the
   reference), then this value should be ‘R’.  --->>
   - If the field has one value for each possible allele (including the
      reference), then this value should be ‘R’.  The order of the values
      corresponds to the reference allele first, and then to the alternate
      alleles in their order


   -

   If the field has one value for each possible genotype (more relevant to
   the FORMAT tags) then this value should be ‘G’. --->>
   -
      - If the field has one value for each possible genotype (more
      relevant to the FORMAT tags) then this value should be ‘G’. The order of
      values corresponds to the order of possible genotypes as
prescribed in  the
      GENOTYPE ORDERING section below.
