### ISSUE TITLE
VCF: Are INFO fields allowed to appear several times in the same variant?

### ISSUE THREAD

**Issue by jmmut** [samtools/hts-specs#157]
Hello, I'm working on a tool that processes VCFs and I wonder how to handle the case that an INFO field is present several times in the same row, e.g. `xxx=1;xxx=2`.

I think that this should be incorrect, reporting the VCF as invalid, but I don't see that the specification states it explicitly, so maybe (I hope not) it is in fact allowed.

I admit that it is unlikely to ever find this case, but I think it should be stated explicitly anyways.

So, in case it is not allowed, I suggest to add to the INFO description something like 
> No INFO key is allowed to appear more than once in a single line.

**Comment by pd3** [comment]
That's correct, the tags must appear only once

**Comment by jmmut** [comment]
Ok, thanks for the speed answering, but is this going to be changed? I can do a pull request if so.

**Comment by jmarshall** [comment]
Which document are you looking at?  VCFv4.3 has the following, which is intended to cover this:

> INFO keys must match the regular expression `^[A-Za-z ][0-9A-Za-z .]*$`, duplicate fields are not allowed.

**Comment by jmmut** [comment]
Oh, my fault, I mistook 4.2 for 4.3, you're right. Sorry for the issue noise.
