### ISSUE TITLE
1000G reserve key appears to break with new regular expression

### ISSUE THREAD

**Issue by jamesemery** [samtools/hts-specs#164]
I noticed that in the current version of the VCFv4.3 spec in section 1.6.1 (8) it has a new regular expression for INFO keys that enforces that the first character is alphabetical but on the same page it lists 1000G key as being one of the reserved keys. This appears to be invalid according to the new character restrictions.

**Comment by pd3** [comment]
Ah, you are right, that's unfortunate. The options are either 1) invalidate the existing tag or 2) make the tag names more permissible. What do people think?

**Comment by lbergelson** [comment]
Is there any reason to restrict the first character in the tags more than the rest of the characters?  Variable names don't allow digits in the first position to avoid parsing confusion with numeric literals, but that isn't a problem for us.  It seems like having the first character follow the same restrictions (alpha-numberic and underscore) as the rest of the tag should be ok.  I might be missing some reasoning behind the first character restrictions though.

**Comment by pd3** [comment]
I think the motivation was quite similar - to allow querying of VCFs using boolean expressions. If tags like 123 are allowed, the querying language needs to escape tag names somehow.

**Comment by pd3** [comment]
How about making the tag names more permissible and require that there are non-numerical character(s) in the tag name, but not necessarily at the first position?

**Comment by lbergelson** [comment]
If we follow the "must contain some alpha character" we should be sure to account for things like 0xFFFF, 30E5, and 0b001 which are valid numeric literals.  Seems complicated. 

I like the "allow 1000G as a special legacy value" approach.

**Comment by pd3** [comment]
Anyone else wants to comment on this?

**Comment by cyenyxe** [comment]
Just that we need to create the PR to add that "1000G is allowed as a special legacy value".
