### ISSUE TITLE
Working VCFv4.3 Implementation?

### ISSUE THREAD

**Issue by jamesemery** [samtools/hts-specs#165]
I am working on updating HTSJDK to support VCFv4.3 and I want to test my new implementation against other working implementation output. Does anybody know where VCFv4.3 is implemented in a working fashion?

**Comment by jmarshall** [comment]
I suppose the canonical implementation is HTSlib, but you'd have to clarify what you mean by “in a working fashion”.

I would suggest taking this question to the [vcftools-spec mailing list](https://lists.sourceforge.net/lists/listinfo/vcftools-spec) or possibly a more populous mailing list such as [samtools-devel](https://lists.sourceforge.net/lists/listinfo/samtools-devel).
