### ISSUE TITLE
How do I create a pdf from the latest VCFv4.3.tex?

### ISSUE THREAD

**Issue by thefferon** [samtools/hts-specs#174]
I like to view VCF in pdf format; I also like to use the latest version, with all recent corrections made. The VCFv4.3.pdf file that is available is a year old.

I work on a Mac, have installed MacTeX, and use TeXShop to open the file VCFv4.3.tex. However when I try to typeset the document I encounter errors – the first of which says, "File 'VCFv4.3.ver' not found." I also find that the .png figures are not found.

I tried cloning hts-specs and opening VCFv4.3.tex from there, thinking TeXShop would then be able to find the necessary files - but it didn't.

Can someone tell me how to generate a pdf of the latest VCFv4.3 spec, please?

Thanks

**Comment by pd3** [comment]
Hi, this works for me:

    git clone https://github.com/samtools/hts-specs.git
    make

You need to have `pdflatex` installed and `git describe` gets called.

**Comment by thefferon** [comment]
Thanks @pd3 ! That worked beautifully.
