### ISSUE TITLE
Add 'BGISEQ' as a valid value of PL in @RG header record

### ISSUE THREAD

**Issue by chenyu600** [samtools/hts-specs#178]
As we all known, `BGISEQ-500` as an NGS platform have applicated in scientific research and clinic test. But in bam file's header recorder `@RG`, there is no proper option for `PL`, and cause some problem in the downstream analysis (e.g. GATK BQSR). So I advice add `BGISEQ` as a valid option

If you want to know more information of BGISEQ-500, there are tow demo data:
[BGISEQ-500 WGS demo FASTQ data](http://www.ebi.ac.uk/ena/data/view/PRJEB15427)  
[BGISEQ-500 RNA-seq demo FASTQ data](http://www.ebi.ac.uk/ena/data/view/PRJEB15426)

**Comment by yfarjoun** [comment]
Would BGI be enough given that "SEQ" is simply short for "sequencer"?

**Comment by jkbonfield** [comment]
Good question.  It's currently a mixture of companies, technologies and platform names.  There is PM to distinguish the specific model (such as BGISEQ-500).

I guess it depends if we want to consider "BGISEQ" to be a "platform" incase BGI later come up with for example a "BGIPORE" platform.  My inclination is to stick with BGISEQ therefore, but it's not a strongly held view.

**Comment by jmarshall** [comment]
Unfortunately we've neglected this request for a long time and hopefully @chenyu600 or someone from BGI or who uses it will return and offer some advice.

It would appear that BGI is the institute/company, there are instruments including BGISEQ-500 and BGISEQ-50 (hence the requested `BGISEQ`), and the technology used is (now) called DNBseq (hence `DNBSEQ` perhaps).

**Comment by colinhercus** [comment]
BGI sequencers are now sold by MGI Tech and they have these models...

Product Model | DNBSEQ-T7 | DNBSEQ-G400（previously MGISEQ-2000) | DNBSEQ-G50（previously MGISEQ-200) | BGISEQ-500

**Comment by jmarshall** [comment]
The (probably incomplete) table row at [wikipedia](https://en.wikipedia.org/wiki/DNA_sequencing#High-throughput_methods) and the [description later in the article](https://en.wikipedia.org/wiki/DNA_sequencing#Combinatorial_probe_anchor_synthesis_(cPAS)) may be of interest.

**Comment by splaisan** [comment]
If of any effect I upvote this request
It would indeed be nice to add 'BGI' as a valid key for PL.
Their error model is not identical to Illumina and is likely to evolve in the near future

**Comment by jmarshall** [comment]
Do you have more information about how their error model is likely to evolve, and in what “near future” timeframe?

**Comment by splaisan** [comment]
Hi John,

I do not have more info but they are finishing a new longer read technology based on proteins which will not have the same biases as Current ones
It will surely be as different as older sequencing platforms (having a key) are from the curren Illumina if not even more.
Having at least one BGI key will then be best in order to allow downstream tools make a difference between library prep and sequencing methods
Besides, why allowing Pacbio and ONT and not BGI? This is not fair.
I now use ‘Illumina' to avoid GATK complains rather than BGI which would be more correct on the long term

S

**Comment by jmarshall** [comment]
Indeed it is unfortunate to have omitted this manufacturer/technology, which is why it's being fixed.

However it sounds like in future we will need two values representing different BGI-originated technologies; cf https://github.com/samtools/hts-specs/pull/454#issuecomment-553945542.
