### ISSUE TITLE
Variant type

### ISSUE THREAD

**Issue by david4096** [samtools/hts-specs#183]
VCF has improved greatly in its ability to represent structural variants, but the variant type is used often enough that it is being considered as an addition to the GA4GH spec [here](https://github.com/ga4gh/schemas/pull/772).

Variant callers provide some variant type metadata, for example in the [TCGA VCF spec](https://github.com/ga4gh/schemas/pull/772). Could we add a column that let's the spec handle some canonical variant types, and then allow it to be extended using metadata IDs. This new VCF column would allow callers to optionally add `SNP`, `INS`, `SVT`, etc.

In the spec we could provide the specific mapping to sequence ontology terms. By allowing callers to define their own variant types, we can allow for them to present the greatest number of features while supporting the basic use case of exchanging the interpreted semantic change to the genome. The `ALT` column would continue to be used in the way it has when adding metadata IDs in place of alternate bases.

[TCGA VT field](https://wiki.nci.nih.gov/display/TCGA/TCGA+Variant+Call+Format+%28VCF%29+Specification)

1kgenomes uses: `##INFO=<ID=TYPE,Number=A,Type=String,Description="Type of variant">`

Used in some annotation packages: https://bioconductor.org/packages/devel/bioc/vignettes/VariantAnnotation/inst/doc/VariantAnnotation.pdf

I believe this is an often enough named field in the info that having it in the spec will improve the field's understanding of the types of variants being called. It doesn't require any specific software and is a value that some callers and most annotators would produce.

**Comment by yfarjoun** [comment]
Changing the fixed columns of the VCF is a disruptive change to the VCF spec. Given that TYPE is already a standard tag in VCF spec, can you explain more clearly how this proposal would benefit the community?

also, I'm not sure I understand what you mean by "It doesn't require any specific software".

**Comment by david4096** [comment]
Thanks! I think this might be a case of misinterpreting the spec, so bear with me. When the alternate bases "fit" into the VCF column, they are added. It is left up to variant annotators whether it's a SNP, DUP, or insertion.

**Comment by cyenyxe** [comment]
The number of types currently available in the `SVTYPE` is quite limited (DEL, INS, DUP, INV, CNV, BND) and it has issues such as #142. It could be worth exploring more specific representations of variant types.

**Comment by yfarjoun** [comment]
That would be a different proposal altogether, and I would be much more on board with that!!

**Comment by david4096** [comment]
My hope is that in doing so, the connection to existing controlled vocabularies for variant types (the Sequence Ontology) can be used.

**Comment by d-cameron** [comment]
Using SO vocabulary is particularly problematic as for some terms (eg breakpoint) VCF has a definition that does not match the SO definition.
