### ISSUE TITLE
Definition of INFO/FORMAT MQ field

### ISSUE THREAD

**Issue by cyenyxe** [samtools/hts-specs#188]
The type of the MQ field is inconsistent across the specification:

* INFO: Type not specified.
* FORMAT: Type is Integer, but an RMS should be a Float?

@pd3 previously mentioned in #185 that 

> FMT/MQ is an integer because of size considerations - integers can packed into 8 bits and the size savings can be significant. With INFO fields it does not matter. But I am equally happy with an integer INFO/MQ.

**Comment by cyenyxe** [comment]
GATK uses Number=1, Type=Float.

**Comment by mp15** [comment]
Quick off topic aside but possibly relevant in the Integer vs Float discussion: How many of these per field space savings compress away or would compress away if we made a column oriented VCF like CRAM? I'm just wondering whether we are really saving space or if they might not be a premature optimisation?
