### ISSUE TITLE
Definition of INFO SB field

### ISSUE THREAD

**Issue by cyenyxe** [samtools/hts-specs#189]
The INFO SB field is simply described as "Strand bias", without Number or Type specified.
 
[The GATK documentation](https://software.broadinstitute.org/gatk/gatkdocs/3.5-0/org_broadinstitute_gatk_tools_walkers_annotator_StrandBiasBySample.php) defines it as Number=4,Type=Integer.

**Comment by pd3** [comment]
Then let's use that - Number=4,Type=Integer
