### ISSUE TITLE
Typo in BCF spec 

### ISSUE THREAD

**Issue by JackFindhammer** [samtools/hts-specs#211]
When looking into the BCF spec I found a few typo's. 
From 6.4.4  the "1element string" is encoded as 0x**19**, while this should be encoded as 0x**17**
(search for 0x19 gives 9 hits, all of them incorrect) 

This is in all 3 versions of   VCFv4.x.tex

**Comment by pd3** [comment]
Thank you for noticing, this indeed is a typo
