### ISSUE TITLE
Proposal: Read Group BC tag

### ISSUE THREAD

**Issue by magicDGS** [samtools/hts-specs#249]
For each of the reads, the `BC` tag represents the barcode sequence usually detected from the read sequence. Nevertheless, this sequence is suppose to match to some extend the one used for identify the sample/library. Because this concept is tightly linked to the concept of read group, I suggest to add to the optional RG tags the BC indicating the expected sequence for the BC tag.

Like that, one can compare the expected value for the sample/library and the one coming from the sequencer to check if there is some mismatch and identify by barcode the samples.

**Comment by yfarjoun** [comment]
This would be nice, I think. At Broad, we put the barcode in the PU field
of the ReadGroup record as <FLOWCELL>.<LANE>.<BARCODE> and use it together
as a unique identifier, but I agree that making it more "computable" seems
like a Good Thing.

**Comment by jkbonfield** [comment]
Thumbs up in principle, but I think we need people more experienced with all the weird and wonderful combinations that exist to see how it works in practice.

For example, using multiple barcodes per library.  Do we simply state the limitations of this implementation (it doesn't cover it), or define a serialisation method such as BC:seq,seq,seq...?  Is this the sequence added, or the sequence to compare against when decoding?  With different sized barcodes, we may algorithmically want to compare all with the same length, which means adding a bit of adapter sequence while comparing.  Etc.   I'm not qualified to think about all these nuances.

**Comment by magicDGS** [comment]
I was thinking about usign the `BC` for the sequence to compare against when decoding (the one used in the library prep). It does not have to match with the `BC` tag for the read (which is the raw barcode coming from the sequencer), so it can be compared to have statistics about mismatches or to discard not complete matches.

In the case of multiple barcodes, I guess that it should be similar to the definition of the `BC` tag on the read: left to the implementation, recommending hyphen `-` as separator. Maybe it should be stated that it is recommended to use the same separator in the header and the read tag. Like that, it can also be used for decoding as a full string matching without splitting into several sequences.

In my lab, I developed a tool to de-multiplex barcoded files in different formats; currently I am using the `BC` tag on the read against a file provided by the user, and then I assign a read group. It would be nice to be able to store the information on where the assignation come from to keep track that the file was already de-multiplexed and evaluating different algorithms to do it. I was thinking to use a custom `@RG` tag (probably `bc`), but as I believe that there is more people interested on this and it would be nice to have it defined in the specs...
