### ISSUE TITLE
Potentially ambiguous interpretation of character encoding

### ISSUE THREAD

**Issue by eyherabh** [samtools/hts-specs#252]
I find the section 1.2 of VCFv4.3.pdf ambiguous about the encoding of characters with special meaning. Specifically, that section requires that characters with special meaning be encoded using capitalized percentage encoding, but neither seems to say whether that encoding is required only within what fields, nor whether such encoding is restricted to fields or can be used interchangeably with UTF-8 encoding when the special characters are used in their special meaning.
That is, could you please clarify me whether the standard does actually prevent, for example, two columns be separated by "%09"  (three characters) as opposed to '\t' (one character)?
Thank you very much.
Best regards..

**Comment by d-cameron** [comment]
The percent encoding in VCF is based on RFC 3986 and is used in the same manner.

> That is, could you please clarify me whether the standard does actually prevent, for example, two columns be separated by "%09" (three characters) as opposed to '\t' (one character)?

No. Percentage encoding is only used to encode special characters when the unencoded version is disallowed. Allowing %09 as an alternative field separator would reintroduce the parsing ambiguity that percent encoding was added to fix.

**Comment by eyherabh** [comment]
Crystal clear. Thank you very much!
