### ISSUE TITLE
BAM format sequence field parsing

### ISSUE THREAD

**Issue by betteridiot** [samtools/hts-specs#269]
Still combing through the BAM format specs. My lack of CS is going to show with this question, but for the `seq` field of the BAM format, as a 4-bit, high nibble first encoded read, does that mean that I have to make two passes through the array to construct the sequence string (e.g. high nibble transformation for each, then low nibble) or should I just do one pass, making serial transformation of each element (e.g. high nibble and low nibble for one, then continue)?

Or am I completely wrong. I am just puzzled is all...for example, I have an `l_seq` of 31, and therefore my `seq` array is `l_seq + 1// 2` long. That leaves my seq at a length of 16 if I do a high nibble only. Any guidance?

UPDATE: Nevermind. After messing around with samtools for comparison's sake, I found that to recreate the sequence it is high-nibble *then* low-nibble for each element of the array. Sorry for the interruption

**Comment by jkbonfield** [comment]
It's rather terse in description, but short of a complete rewrite (arguably needed!) there isn't a great deal of room for expanding on this other than yet more footnotes.

We will review this soon (see commit https://github.com/samtools/hts-specs/pull/259/commits/9ab9e3a40f36754a3b59991d9d7cf10332732f03, which I'll move into its own PR at some point) so could add some clarification on seq there too.
