### ISSUE TITLE
Clarification on BAM tag boundaries

### ISSUE THREAD

**Issue by innovate-invent** [samtools/hts-specs#273]
The BAM spec has no description of how to determine the byte length of the H and Z tag values.
Is it the same as B where the first 4 bytes are the length?

This should also be clarified for the SAM spec.

Thanks

**Comment by jkbonfield** [comment]
This is an omission then.  They are nul-terminated strings, so should be read up to and including a zero byte value.

**Comment by innovate-invent** [comment]
Thanks,
How are tags delineated in a SAM file?

**Comment by innovate-invent** [comment]
Sorry, I am not sure it makes sense that the H type tag representing a HEX array be terminated with a null byte. Could you clarify?
Thanks

**Comment by jkbonfield** [comment]
Tags in SAM are just tab delimited fields, like everything else.

The H tag type is a bit odd.  It claims to be hex, so you'd think it would just be a byte array in BAM (this was subsequently added for the "B" type, but only much later on).  Instead it is a string of hex digits exactly as in SAM, and hence stored identically to Z.  See footnote 9 for the SAM part of this.  It's also now documented in PR #274 for BAM (it's basically a copy of the text from the SAM part).

Note after B tag type was added,  Picard / htsjdk now silently converts H tags to B,c arrays.  Personally I view this as a bug, but given the number of uses of H out there it's (none as far as I'm aware) it's basically a non-issue.

**Comment by innovate-invent** [comment]
Thanks,
I added a comment to PR #274, basically the H tag is still described as a byte array in the PR.
The footnote is also still a little ambiguous as it is hard to believe that a HEX array would be stored as ASCII and should be a little more explicit about that.

**Comment by jkbonfield** [comment]
In SAM this is less ambiguous as the entire format is textual.  However it is indeed unexpected that the binary BAM holds it in the same ASCII format so it could be more explicit.
