### ISSUE TITLE
A new SAM tag for transcript strand

### ISSUE THREAD

**Issue by lh3** [samtools/hts-specs#276]
Tophat and many RNA-seq mappers output an "XS:A" in SAM. It is either "+" or "-", indicating the putative strand of the transcript the read is sequenced from. It is so widely used and effectively becomes a standard tag in the RNA-seq world. Do we want to add a "TS" (or "ST"; both are available) tag for the same purpose? In practice, I am not sure how many will use the new tag, but better late than never. If you are ok with this, I can send a pull request later.

**Comment by dpryan79** [comment]
To my knowledge, only cufflinks and stringTie have ever made use of the "XS:A" tag. I'm not sure it's worth occupying a tag just for them.

**Comment by lh3** [comment]
I expect for long RNA-seq reads, this tag will be used much more often, for example to generate BED12 and GFF. Some users are requesting it (lh3/minimap2#88). In the old days, when we map ESTs, transcript strand is critical information when is unknown.

**Comment by yfarjoun** [comment]
can this information not be determined form the read ordinality and the mapping orientation?

**Comment by lh3** [comment]
What's read ordinality? Either way, for non-stranded libraries, transcript strand can't be inferred.

**Comment by jkbonfield** [comment]
Even if it doesn't get a large amount of use, the fact that more than one program wishes to generate this tag and that users have requested it makes me think it should be accepted.

I'm happy with either TS or ST as a tag type.

**Comment by lh3** [comment]
Closed via PR #292.
