### ISSUE TITLE
Clarification required on BGZF extra field

### ISSUE THREAD

**Issue by innovate-invent** [samtools/hts-specs#277]
[This line](https://github.com/samtools/hts-specs/blob/5471fb9f70c9100cc135eb2f14422e696375b6b4/SAMv1.tex#L740) is ambiguous.

Does BSIZE describe the total block size including header and trailer or is it strictly the size of the CDATA field?

Thanks

**Comment by jkbonfield** [comment]
Sorry, but I don't think this is ambiguous in the way you describe.

The CDATA field is stated to be of length BSIZE-XLEN-19 which clearly informs that BSIZE isn't just the length of the CDATA field.  Additionally the entire table is stated to be a block (in "a series of blocks as shown in the following table") and the BSIZE field is describes as "total block size minus 1".  So it is described in two ways to be the full size and not just CDATA size.

The bgzf code has:

```
#define BLOCK_HEADER_LENGTH 18
#define BLOCK_FOOTER_LENGTH 8
...
// zs.total_out being zlib compressed CDATA size
*dlen = zs.total_out + BLOCK_HEADER_LENGTH + BLOCK_FOOTER_LENGTH;
...
packInt16(&dst[16], *dlen - 1); // write the compressed length; -1 to fit 2 bytes
```

So it's implemented exactly as described in the specification.  (18 in the header length includes the 6 for XLEN, so it's 12 + 8 = 20, giving BSIZE-XLEN-19 as CDATA length).
