### ISSUE TITLE
Clarification on BGZF block boundaries

### ISSUE THREAD

**Issue by innovate-invent** [samtools/hts-specs#278]
I am not sure if this is implied anywhere in the spec.
Are there expected behaviors for block boundaries on the uncompressed data?
For example can a record span multiple blocks? 
Is arbitrarily dividing the uncompressed data buffer into 64KB blocks and compressing acceptable?

**Comment by jkbonfield** [comment]
Yes records can.  Indeed if a record is larger than a block then it has to. The bgzf layer is completely format agnostic and a totally separate spec to BAM really.

Modern Samtools and I think Picard now start a new block if the current read doesn't fit in the remainder, which can help with parallelism, but it's not something you can assume.
