### ISSUE TITLE
Clarification on BAM block_size

### ISSUE THREAD

**Issue by innovate-invent** [samtools/hts-specs#279]
I may have bad data but the set block_size is significantly smaller than the total size of the BAM record.
It is described as "Length of the remainder of the alignment record".
Can anyone clarify exactly what data block_size is representing.

Thanks

**Comment by innovate-invent** [comment]
After dissecting the htslib code and a bam file it appears that the block_size = total number of bytes for the record - sizeof(block_size).
Is this correct?

**Comment by jkbonfield** [comment]
Yes - it is the remainder of the record, after itself. Ie everything bar block_size.  The code isn't easy to follow as it does lots of small reads, but I think the specification text is correct if a bit terse.

I added "Total length of the alignment record, excluding this field" instead to PR#274, for review by the other maintainers.
