### ISSUE TITLE
Clarification on SAM empty lines

### ISSUE THREAD

**Issue by innovate-invent** [samtools/hts-specs#282]
This may seem obvious but I can't find it explicitly stated anywhere.
Are SAM parsers expected to handle empty lines? 
ie '\n\n' at the end of a record or header.

Thanks

**Comment by jkbonfield** [comment]
Blank lines are not legal.  I think this is implicit in "Each alignment line has 11 mandatory fields" (and similarly for header equivalent).  A blank line does not have 11 fields.
