### ISSUE TITLE
CRAM: unclear spec for BYTE_ARRAY_LEN

### ISSUE THREAD

**Issue by lomereiter** [samtools/hts-specs#30]
These lines don't quite make sense:
https://github.com/samtools/hts-specs/blob/c923d4f075da6030989875723fdc405525a5d6ad/CRAMv2.1.tex#L1622-L1635
The parameters don't include any encoding, though they should according to the informal description.

**Comment by jmthibault79** [comment]
Resolved by #359

**Comment by jkbonfield** [comment]
We're currently working through old PRs/Issues slowly to try and get the backlog down, but it's a challenging process.  Good spot and thanks. :-)
