### ISSUE TITLE
Should we add a CI  that checks that a PR "compiles" and provides URL to the pdfs?

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#310]
This seems to be easy to accomplish using Circle-CI (but not travis). 
If people have opinions about this, please chime in.

Yossi.

**Comment by cyenyxe** [comment]
Just curiosity, but why is it not easy with Travis?

**Comment by jmarshall** [comment]
This has now been implemented by @yfarjoun's PR #328.

We may in future wish to revisit this and implement it natively using GitHub Actions…
