### ISSUE TITLE
SAM/BAM spec: Recent Update

### ISSUE THREAD

**Issue by betteridiot** [samtools/hts-specs#316]
First, great job on updating some of the language in the new SAM/BAM spec. I really like how the tags and SEQ sections were expanded.

However, with the recent change I have 2 questions:
1) Is there an archive anywhere of prior versions of the spec?
2) Do the v1.8 changes to the BAM format break existing pipelines that don't use htslib? For example, `bin_mq_nl` is no longer a single field, replaced with `bin`, `mapq`, and `l_read_name`.

**Comment by lbergelson** [comment]
Maybe we should add tags to the git repo for different versions of the spec?

**Comment by betteridiot** [comment]
Yeah, as soon as I sent the "issue" I realized that the order was still preserved, and all I was doing was masking and shifting. Seems obvious, but I have been staring at the same spec for months now and got worried when I saw the change, Thank you.

As far as the versions of the spec, the only caveat I would add is that it expects users to know git. If I point someone to the spec, they may not be using the most recent and have no idea how to get to their version. Just an edge case is all.

**Comment by jmarshall** [comment]
Changes to the SAM specifications are almost entirely either clarifications or additions. The format remains backwards compatible with its initial version. The version number to be (optionally) recorded in files gets bumped to indicate additions that may cause compatibility issues for old code, but such additions are few (and are listed in the history appendices). In practice, implementations don't emit the VN version number carefully or take advantage of it, so it is mostly a theoretical construct.

So in practice there is very little reason to not be looking at the most recent SAM specification. It describes the same thing as earlier editions, only more clearly. Those who want to verify that or need more historical detail than the appendices provide are about the only ones who would need to look at old editions. This is a small enough need that pointing them at PDFs or TeX source in git or the GitHub repository web view seems sufficient.

(The fields you mention are a case in point: exactly the same data layout is being described, only more clearly.)

Similarly IMHO there is little reason to add tags to facilitate looking at old SAM specifications. The few who desire to can find those commits easily enough with `git log -SVN:1.5 -- SAM*.tex` (and so on) or `git blame`. Really the logs (`git log` and `diff`) nearby are more interesting than the exact commit at which the version was bumped.

Similar arguments can be made for the other specifications: CRAM and VCF. Except they keep additional copies of all their text in separate v2.1/3 or v4.1/4.2/4.3 files in HEAD, so the question is mostly moot for them anyway.

**Comment by jkbonfield** [comment]
There was some discussion in https://github.com/samtools/hts-specs/issues/194 about adding tags and how we could use them with git describe to identify which version any commit is (this can be useful sometimes as the logs aren't always as easy to identify as possible).  It moved on to version history though in the specification, which is definitely a big improvement.

I guess it's still a valid question as to whether adding tags would also be useful for tracking.  It's muddied by the fact there are lots of specs and tags apply to all documents.  If we don't like the idea, then we should close #194 as the rest of it has been resolved.

**Comment by jmarshall** [comment]
SAM question about `bin_mq_nl` has been resolved; question about archival spec editions and/or git tags in this repository already being discussed in #194. So I think we can close this one.
