### ISSUE TITLE
Unify VCF spec

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#32]
At the moment, there are separate VCFv4.1 and VCFv4.2 specs with very little difference between them -- and it is hard to figure out by reading them just what the difference between them is.

Having two near-duplicate documents also means that typos have to be fixed twice, etc.

It would be better if these were unified into a single document, so that the common things could be seen to be common.  And it would note where there are differences between the point-releases, e.g., it would say that `Number=R` is a 4.2 feature.

**Comment by cyenyxe** [comment]
A changelog has been added at the end of the VCF v4.3 specification, and it has been agreed offline not to merge all the documents into one so I will close this ticket.
