### ISSUE TITLE
BND is missing from the valid values for SVTYPE in VCF 4.3

### ISSUE THREAD

**Issue by jmmut** [samtools/hts-specs#347]
The list at https://github.com/samtools/hts-specs/blob/master/VCFv4.3.tex#L548 is missing BND, even though it's stated as valid value in 4.2 and 4.1, and used in lots of examples in 4.3.

It's seems this value was lost in a formatting commit: https://github.com/samtools/hts-specs/commit/e6f3567c7ada44f94e429c9642edd93d75528dbd#diff-6fd0045c2c7902d4181b2e8d315cc56dR500

Should the BND item be added to that list?

**Comment by lbergelson** [comment]
I think you're right that it was removed accidentally.  It's restored in https://github.com/samtools/hts-specs/pull/266, but if necessary we could open a quick PR to do it sooner.
