### ISSUE TITLE
Conflicting defintions for <INV> in VCF spec

### ISSUE THREAD

**Issue by glennhickey** [samtools/hts-specs#375]
In Section 1.6.1 of the [VCF spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf), under 4. REF it says, 

*"If any of the ALT alleles is a symbolic allele (an angle-bracketed ID String “<ID>”) then the padding base is required and POS denotes the coordinate of the base preceding the polymorphism."*

But the inversion example in Figure 8 contradicts this as the POS is clearly shown as the first inverted base, and not the preceding base as described above:

![screenshot from 2019-01-24 14-33-56](https://user-images.githubusercontent.com/901102/51704810-fa5fce80-1fe7-11e9-8b9f-0e19633e8a11.png)

So which one is correct?

**Comment by edawson** [comment]
Also referenced here: https://github.com/samtools/hts-specs/issues/173

**Comment by edawson** [comment]
We also posted about this a while back with little hope of resolution it seemed: https://github.com/samtools/hts-specs/issues/173

**Comment by glennhickey** [comment]
Aha, seems I'm late to the party.  I'll close this as it's a duplicate of #173.
