### ISSUE TITLE
Standardise the description of Reference and Alternative alleles in sample details

### ISSUE THREAD

**Issue by aeonsim** [samtools/hts-specs#38]
At the moment various variant callers use a wide range of different formats and methods for describing the number of reference and alternative alleles seen at a site for each sample.

Freebayes - Uses RO,AO - two fields one for Ref observations one for Alt observations
GATK - Uses AD one field with the Ref & Alt alleles comma separated
Platypus - Uses NR, NA - With NR being number of reads and NA being number of alts thus Ref = NR-NA

These annotations are useful for a range of different use cases, as they give some indication of what evidence the variant caller made the call off. Which when combined with additional information from the population or pedigree structure can allow for later improvements to the variant call with out going back to the BAM files.

As such it would be useful if a standard way of describing this information could be decided on and included into the VCF spec, this would greatly simplify the use of VCF files after variant calling.

**Comment by pd3** [comment]
I believe this is resolved by https://github.com/samtools/hts-specs/issues/78
