### ISSUE TITLE
A problem in BCF specification example?

### ISSUE THREAD

**Issue by zhanxw** [samtools/hts-specs#382]
The page 35 of BCF specification has a table to show how to code an example VCF record.
The value of `l_shared` is 54 (0x36), but I added the bytes from CHROM to the end of INFO, and got 52 (0x34). I attached the calculation from my screenshot. 
Is it a problem or did I misunderstand something?

The screenshot shows CHROM takes 4 bytes, POS takes 4 bytes, ....
The summation is 52, not 54 as shown in the specification. 

<img width="905" alt="screen shot 2019-02-16 at 4 13 44 pm" src="https://user-images.githubusercontent.com/157832/52905854-e2a1f180-3205-11e9-90b8-5e7b88918841.png">

**Comment by jmarshall** [comment]
You are correct. Other problems with this table:

* ID should be **0x57** 0x72 0x73 0x31 0x32 0x33.

* HM3 flag likely should be 0x11 0x51 **0x00** (see #384), which would make `l_shared` 51 (0x33).

* The AA key row should be 0x11 **0x53**.

And similarly for ID, AA, etc in the preceding sections.
Also in the table at §6.3.1, a typo has merged the ID and REF+ALT rows.

**Comment by zhanxw** [comment]
Thanks for the update.
