### ISSUE TITLE
hts-specs-bot triggered only for PR branches in the samtools/hts-specs repo

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#399]
Compare PRs #397 (from jkbonfield/hts-specs@CRAM_index) and #398 (from samtools/hts-specs@jt_container_header).

The robot has only generated PDFs for and commented on the latter. It would appear that it's not being triggered for PRs based on branches outwith this samtools/hts-specs repository.

**Comment by yfarjoun** [comment]
I turned on building on forks....this should be fixed. 

I also added a noop commit on #397 to see if that triggers a build (it did) 

Sorry @jkbonfield I hope you don't mind...

**Comment by yfarjoun** [comment]
I also had to pass "secrets" to the forks, which I think is OK since the only secret we have is the auth token for the bot which allows it to comment...so in the worst case some bored person will abuse the auth to make comments on github...which they already can.

**Comment by jkbonfield** [comment]
> I turned on building on forks....this should be fixed.
> 
> I also added a noop commit on #397 to see if that triggers a build (it did)
> 
> Sorry @jkbonfield I hope you don't mind...

No problem.  Easy to squash such things down when we merge.
