### ISSUE TITLE
Circular chromosomes in @SQ header

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#403]
It is occasionally suggested that it would be useful to have a convention for annotating reference sequences as being **circular**. See for example [this 2011/12 samtools-devel thread](https://sourceforge.net/p/samtools/mailman/message/28372847/) and [this tweet](https://twitter.com/nilshomer/status/1119381973393260545). There are further questions about how to represent mappings across the “join” in a circular chromosome (as mentioned in that thread), but being able to represent the concept in SAM at all is a useful first step.

For example, this could be

    @SQ    SN:MT    CI:true

for Circular—true, or perhaps more self-explanatorily and flexibly something along the lines of

    @SQ    SN:MT    TP:circular

for Molecule Topology—circular (which would have a default implied value of _linear_).

**Comment by yfarjoun** [comment]
Sounds like a nice addition. I don't know offhand of other topologies that we would want to include...unless we want to eventually allow knot notations... (http://katlas.math.toronto.edu/wiki/The_Rolfsen_Knot_Table) I would be in favor of a boolean option.

**Comment by jkbonfield** [comment]
It's a nice idea and I don't see a problem with adding it, even if downstream tools don't *yet* support it.  Add it and there's a chance that'll happen.

Ancient history: Way back in earlier job we found this notion useful; eg see page 274 (actual 294) of http://nebc.nerc.ac.uk/bioinformatics/documentation/staden/doc/manual_unix.pdf.  In gap4 if a contig reference was marked as circular then the editor would permit scrolling beyond the end and wrapping around to the start.  You could also define where the starting point was.

Both of these were feature requests from people working on studying the Mitochondrial genomes, for which the standard reference sequence at the time just happened to have base number 1 in the hyper variable region, so people often rotated the genome so alignments to that variable region (which was the thing under study) worked.

**Comment by colinhercus** [comment]
Can we use tp:[circlar|linear] to be consistent with grch38 fasta tags

>chrM  AC:J01415.2  gi:113200490  LN:16569  rl:Mitochondrion  AS:GRCh38
tp:circular

**Comment by jmarshall** [comment]
>```
> >chrM AC:J01415.2 gi:113200490 LN:16569 rl:Mitochondrion AS:GRCh38 tp:circular
>```

@colinhercus: I guess this is from ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/ GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/ which contains [README_analysis_sets.txt](http://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/README_analysis_sets.txt) describing the various tags used (see §4), several of which are SAM `@SQ` fields brought across to FASTA:

> …AC, gi, LN, rg, rl, M5, AS, hm…
> tp: topology
>    - circular for chrM and chrEBV
>    - not present for linear chromosomes and scaffolds

For a definition in SAM `@SQ` we'd want to make the tag uppercase,¹ but this is certainly motivation for the TP / Topology terminology.

----
¹ “Tags containing lowercase letters are reserved for local use and will not be formally defined in any future version of this specification.”

**Comment by colinhercus** [comment]
Novoalign copies FASTA lower case tags across to the @SQ so we already have
tp:circular.

**Comment by nh13** [comment]
I’d love this addition to made to the spec. I think an upper case is appropriate as lower case tags are reserved for local use (as @jmarshall cites in the spec). I have an aligned that I am working on for a very long read application that will need to map across the origin. I’ll leave any changes to the spec about how to represent alignments across the origin in a circular reference for later (currently split the alignment into two).

**Comment by yfarjoun** [comment]
I commented in the PR...but I'll comment here too:

One thing is troubling me: If two people have a two different versions of a reference sequence, one which is TP:circular and the other is not, they will have the same md5 which will mean that refGet will clash, and other sanity checks will fail. Should we redefine md5 for TP:circular in some way to avoid this?

For example: 
```
For the purposes of calculating md5, a TP:circular reference will be appended a '$' sign at the end. Example:
>chr1
CTCAACCACTTGAGCAAACTCCAAGAC
has md5 of 4ac2dee8e6ac06422295df0320981c70
but 
>chr1 TP:circular 
CTCAACCACTTGAGCAAACTCCAAGAC
has md5 of de8fd4b0606b285e11251b538b27ce76
```

**Comment by peterjc** [comment]
@yfarjoun seems like long term I'd *want* the meta-data clash to be be spotted and treated as an error. In the short term (since the circular tag will take a while to be adopted), have the sanity checker treat this as a warning only? Am I missing something (not familiar with the implementation details of refGet)?

**Comment by jmarshall** [comment]
Closed as the `SQ-TP` header field has now been merged. See https://github.com/samtools/hts-specs/pull/405#issuecomment-490068063 and following for the remainder of the MD5 concern discussion.
