### ISSUE TITLE
VCF spec should highlight INFO/END's use in indexing

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#425]
The VCF specification's §1.6.1's Table 1 simply describes END as

    END    1    Integer    End position (for use with symbolic alleles)

and describes its value in more detail later in §3 for structural variants:

> For precise variants, END is POS + length of REF allele − 1, and the for imprecise variants the corresponding best estimate.

Readers would not guess from this that END, when present, provides the size of the interval that the variant is located in — and both htslib and htsjdk use it when constructing indexes for VCF/BCF files. So in fact it is vital that this field, if present, is correct and is used with the intended meaning.

The specification should highlight END's use in indexing. Ideally the specification should have a more detailed description of END's value.

**Comment by jmarshall** [comment]
For example, gnomAD's SV files use END for their own purposes with a different meaning and value. It was recently noticed that this breaks `bcftools view` with a query region (hat tip @lindenb): see [this twitter thread](https://twitter.com/yokofakun/status/1143451289130590209), [this biostars posting](https://www.biostars.org/p/386345/), and macarthur-lab/gnomad_browser#140.

**Comment by cwhelan** [comment]
There has been some discussion about fixing this as part of https://github.com/samtools/hts-specs/pull/266

**Comment by jmarshall** [comment]
@cwhelan: In particular, this comment of yours: https://github.com/samtools/hts-specs/pull/266#discussion_r282908254. I wish I had realised its significance better at the time!

**Comment by jmarshall** [comment]
Delly has also been using END like this for a number of years; see dellytools/delly#159.
