### ISSUE TITLE
Clarification of CRAM external encodings and blocks

### ISSUE THREAD

**Issue by cmnbroad** [samtools/hts-specs#426]
There are some inconsistencies in the CRAM spec around the use of the word  “external”, probably due to evolution of the spec over time. I’d like to make a PR to resolve them, but in some cases I’m unclear on the intent.

The text alternately refers to “the external  encoding” (singular), “external encodingS” (plural), and “external blocks". Its not always clear which encodings are considered "external"; whether “external” is actually a property of (one or more) encodings, or just of the containing block; and what if any restrictions there are on the relationship between encoding type and block type. A few quotes:

From “Section 3 Encodings”: 
> Encodings may have parameters of different types, for example _the external encoding_ has only a single parameter, integer id of the external blocks

Then later:
> _Each external encoding_ has an id parameter which must be one of the external block content ids.

From Section 8.1 “Block Content types”: 
> CORE is defined as “bit stream of all encodings except for _external_" (lower case)

From Section 8.1“Block Content ID”:
> There are two types of data blocks: core data blocks and external data blocks.The difference between core and external data blocks is that core data blocks consist of data series that are compressed using bit encodings while the external data blocks are byte compressed 

Elsewhere:

- There is an encoding called EXTERNAL that has a content id parameter.
- The BYTE_ARRAY_STOP encoding has an “external content ID” parameter
- The BYTE_ARRAY_LEN encoding does NOT have an external content ID parameter 
- There is a block content type called EXTERNAL_DATA, defined as containing “data produced by external encodings”

Presumably EXTERNAL, BYTE_ARRAY_STOP, and BYTE_ARRAY_LEN are all “external” encodings (?), and are used in EXTERNAL_DATA blocks, but are they restricted to EXTERNAL_DATA blocks ? Is it the case that the remaining encodings are intended to be “CORE” (is their use permitted in an external block )?

Htsjdk’s implementation is an interesting case. For tag values, it uses a BYTE_ARRAY_LEN encoding, which is a nested encoding, and splits the sub-encodings between core and external blocks by Huffman-encoding the array length into the core block (indeed, that is the ONLY thing htsjdk writes to the CORE block), and putting the array itself into a separate external block. If this is permitted, it it challenges the notion that an encoding can/should be categorized as either core or external.

Any insights appreciated.

**Comment by jkbonfield** [comment]
It's a really confusing term and I don't know where it came from.

However I see there is potential for confusion.  Is "external" any block other than CORE, or any block  with encoding EXTERNAL?

The answer lies in realising that BYTE_ARRAY_STOP and BYTE_ARRAY_LEN don't themselves specify block IDs.  Instead they refer to sub encodings.  Eg BYTE_ARRAY_LEN is an encoding which is described as two sub-encodings for the byte array itself and the length.  These may be BETA, GAMMA, HUFFMAN, etc using CORE or they may be EXTERNAL in which case it is non-core.

Thus the question above is wrong as there is no either-or here and both conditions are infact the same thing.  Hence the statements, while perhaps being confusing, are internally consistent as far as I can see.  I think the main problem is simply the name.  There is nothing external about EXTERNAL encoding at all.  I assume the thinking was that we have our own codecs written as part of CRAM (beta, huffman and so on) or we utilise external libraries (gzip, bizp2) instead.

If you can find better wording I'm happy to review a PR.

The sad bit here is it misses a trick.  It's perfectly justified to use an "internal" codec to convert an array of integers to a bit-stream to be stored somewhere other than CORE and then use an "external" compression codec to further compress it.  In that way we'd consider the internal codecs to be transformations and the external codecs to be compression methods.  Maybe for V4. :)

**Comment by cmnbroad** [comment]
I think most of the confusion is because there is an encoding called "EXTERNAL", but its not the only encoding that qualifies as "external". So references to 'external encoding" are ambiguous (ie., BYTE_ARRAY_STOP has an external content ID param, just like EXTERNAL does). So I made the smallest clarifying change I could, which is to always refer to the EXTERNAL encoding using all caps, and always use plural "external encodings" when referring to external encodings as a group.

**Comment by cmnbroad** [comment]
Closing via #452.
