### ISSUE TITLE
vcf not slicing in htsnexus 

### ISSUE THREAD

**Issue by shubhamLondhe** [samtools/hts-specs#428]
I know, this is not the right repository for this issue but, I needed an htsget implementation for slicing vcf files, so I used https://github.com/dnanexus-rnd/htsnexus which is great but, it doesn't slice the vcf files accurately, can anyone help me in this use case. Thanks

**Comment by mlin** [comment]
We'll discuss this on https://github.com/dnanexus-rnd/htsnexus/issues/30 and ga4gh TC. thanks
