### ISSUE TITLE
Please clarify if the INFO field can be left empty or the missing value should be used

### ISSUE THREAD

**Issue by eyherabh** [samtools/hts-specs#439]
Section 1 of VCF 4.3 says that zero-length fields are not allowed, and that the period should be used instead, so it may seem redundant to state that in the description of the INFO field in section 1.6.1. However, the need for using a period (also referred as missing value) is mentioned there for every other non-required field (i.e. ID, QUAL, FILTER). Therefore, the fact that it is not explicitly stated for the INFO field left me under the impression that the INFO field can be left empty.
Could you please clarify that? Thanks

**Comment by pd3** [comment]
INFO is the same, cannot be left empty. Only FORMAT and sample columns may be omitted when no samples are present.

**Comment by eyherabh** [comment]
Thanks! Submitted clarification.
