### ISSUE TITLE
clarify section of SAM1 spec explaining combining bins with linear index

### ISSUE THREAD

**Issue by kortschak** [samtools/hts-specs#45]
In the text of SAMv1.tex:

```
Given a region [rbeg,rend), we only need to visit a chunk whose
end file offset is larger than the file offset of the 16kbp window
containing rbeg.
```

clarify whether the given region, [rbeg,rend) is a query or an alignment. If the region is a query the statement is not true since we need to visit all chunks whose end file offset is larger than the file offset of the 16kbp window containing _any position_ in [rbeg,rend) since we may have alignments in the specified region that are not in the first tile of the linear index.

**Comment by jmarshall** [comment]
The region is a query, and the statement is now true following the correction of the preceding sentence (which describes the construction of the windows) in df3bcefaaa06467b375f98ac9da77bc83ffff340.

With that correction made, I'm thinking this paragraph is now suitably clear?

We apologise for overlooking your bug report all this time. I would have saved myself several frustrating days of debugging in samtools/htslib#405 if I had fixed the spec in 2014!
