### ISSUE TITLE
Clarify NM and MD creation in CRAM

### ISSUE THREAD

**Issue by jkbonfield** [samtools/hts-specs#453]
The CRAM decoder can compute MD and NM on the fly for files using reference based compression (either external or embedded).  Both Java and C implementations do this.  It appears I added code to do this in Feb 2013 https://github.com/jkbonfield/io_lib/commit/51c2610a726fccedb42e75b214161c1d0afa9daa and Vadim's predates that in Oct 2012 https://github.com/enasequence/cramtools/commit/181f75237e9b9a85cdc10acf09240c0997ca9e3f

Hence I assume I just copied Vadim's ideas here.

The problem though is any mention of MD and NM is totally absent from the specification itself.  It perhaps seemed trivial initially, but since then I've accrued various tweaks and bits of logic.  Eg:

-  If the tag dictionary already contains MD then we have a verbatim MD string encoded for that record.  Don't auto-generate it.  I did this to silence the whingers who complained CRAM wasn't round tripping correctly.  (it wasn't as it bug fixed MD strings that overhang the end of the reference but apparently that isn't desireable.)

- We have no way of knowing whether MD and NM were previously on the record.  Hence we either always create them or never create them based on command line options.  For V4 prototype I have a strategy of adding MDZ to tag dictionary for MD stored verbatim, no MD anything for do-not-generate and MD* for a request to generate an MD tag.

- There's no way of knowing whether MD is computed using the embedded reference vs the external reference, if both are present and differ!  This is the main reason for this ticket as I went to seek guidance and realised it was absent.

For this last point (this is V4 thinking again) I could consider an embedded consensus differing to the external reference and using the external ref for auto-MD generation so we don't have to store it verbatim when cons vs ref differs.  Or alternatively when we have embedded cons and no external ref, but have a literal MD tag (perhaps with appropriate flag, eg MDz instead of MDZ?) we use this as a way to learn how the actual reference differed to the embedded one so subsequent reads don't also need to explicitly store MD.  That's a little bit ghastly though! :)

Note RG also falls in this same category, but it's a bit different in construction.

Proposal for spec:

- Explicitly define that tags MD, NM may optionally be computed on the fly.  (Discussion point - does the embedded reference get used in preference to external if external is also avaialable?)
- Explicitly define that RG tag is computed from the RG data series if this is not set to -1.

**Comment by cmnbroad** [comment]
So for v3, it sounds like we just need to update the spec to be explicit that implementations can optionally choose to generate these on read (BTW, htsjdk never does this, though I think it may have in the distant past - it merely preserves them on read and on write whenever they're present). As for embedded, I hadn't thought before about the case where an external reference is provided for a CRAM that has an embedded one, much less one that is different. My inclination is that the embedded one is the correct one to use though. Perhaps there is some other consideration or subtlety that I'm missing ?

**Comment by jkbonfield** [comment]
> As for embedded, I hadn't thought before about the case where an external reference is provided for a CRAM that has an embedded one, much less one that is different. My inclination is that the embedded one is the correct one to use though. Perhaps there is some other consideration or subtlety that I'm missing ?

I don't think you're missing anything.  It should take the embedded reference as gospel for decoding the sequence, although it's unclear what that means for auto-generation of MD / NM.  In practice if the embedded ref differs to the external one the Java code will spot this as it validates the MD5sum against the external reference even when it has an internal embedded one.   This is actually a bug as the spec which states:

> "For embedded references, the MD5 can either be all-zeros or the MD5 of the embedded sequence."

However for now it's potentially useful as we don't have a consistent description of how to handle them differing anyway.

I'll merge #463 and leave this open as a secondary issue to resolve regarding consistency of internal vs external references.  There is a benefit to making them different as it can permit for efficient "reference" encoding vs our consensus, but not without a substantially larger set of changes. so I'll pass on that part for now.
