### ISSUE TITLE
Resolving complex events in VCF requires parsing entire file?

### ISSUE THREAD

**Issue by cmdcolin** [samtools/hts-specs#474]
Hi there,
I was wondering if there are ways to resolve the information about a complex variant (e.g. multiple breakends linked by EVENT or similar) by just "traversing a breakend graph", or not parsing the full file.

If we take the example in VCF 4.3: "5.4.4 Explicit partners." this example illustrates how there can be "disconnected partners", and even when given a PARID, there are no coordinates given for it, so we can't really resolve those partners without parsing the whole file.

**Comment by cmdcolin** [comment]
Options for not parsing the whole file include piecing things together with tabix or storing more data about the event like the SA tag in SAM

**Comment by d-cameron** [comment]
Is this an actual issue with the specifications, or just something that needs to be handled in downstream programs? Complex events such as chromothripsis can have over 1000 breakpoints involved in a single event. A SA-like tag for EVENT will massively blow out the file sizes for anything reasonably complex.

**Comment by d-cameron** [comment]
For example: here is a circos of a relatively simple instance of chromothripsis:
![image](https://user-images.githubusercontent.com/6036536/75220559-cdd24380-57f3-11ea-86d4-6d87ffe2c636.png)

And here is an instance of a complex chromothripsis + breakage fusion bridge
![image](https://user-images.githubusercontent.com/6036536/75220616-eb9fa880-57f3-11ea-93f1-8655224ab129.png)

All those breakpoints are all part of the same complex `EVENT`.

**Comment by cmdcolin** [comment]
I thought that is could be an issue in specification if it represents a weakness in trying to understand the data. I found things like SA tag to be very useful, and clearly it is useful enough to receive some standardization to be included (not sure what the context of it's inclusion was!). The SA tag could also have some N^2 explosion in data if super long reads are very fragmented, but it remains included. If it seems unlikely to have any change I can close for now

**Comment by lbergelson** [comment]
@d-cameron Haven't we talked about including a next in event key with the coordinate of the next element so you don't have to read the whole file?    It seems important to me to be able to pick out all of an event without scanning the entire file.

I thought we'd also talked about the possibility of global per event information going into the file header, but maybe that got shot down as potentially way to much header bloat.

**Comment by d-cameron** [comment]
We're planning to add a next variant to the PSL chaining to enable
traversal of derivative chromosomes but that's different to event grouping.
For example, chromoplexy involves multiple rearrangement across multiple
chromosomes. All part of the same event, but a next variant doesn't make
sense when they're not physically connected.

**Comment by d-cameron** [comment]
PSL phasing including the ability to define SV ordering added to 4.4. Yes, you'll need to parse the whole file.
