### ISSUE TITLE
Track htsget OpenAPI vs textual divergences

### ISSUE THREAD

**Issue by brainstorm** [samtools/hts-specs#475]
This issue [stems from the need to track drift between the programmatic and textual spec]( https://github.com/samtools/hts-specs/pull/472#issuecomment-590665828).

Please redistribute this issue to see which drift issues remain.

/cc @ohofmann

**Comment by jmarshall** [comment]
There is one identified discrepancy (whether the exact `/reads` etc endpoints are recommended or required) and, as agreed during the last meeting, that is being discussed on the mailing list and will be resolved in due course.

IMHO there’s not a lot to be gained by having an open issue to track the possibility of unknown divergences. Better to bring specific individual problems to the mailing list or open them as individual GH issues when they become apparent.

**Comment by brainstorm** [comment]
Fair enough, leaving the google groups link over here and closing:

https://groups.google.com/a/ga4gh.org/forum/#!topic/ga4gh-htsget/PIXqsceCdGo

Might require explicit invitation/email from Rishi or other GA4GH members, it was not open when I just signed up a few days ago.
