### ISSUE TITLE
VCF v4.4

### ISSUE THREAD

**Issue by yfarjoun** [samtools/hts-specs#481]
I'd like to suggest that we start a new VCFv4.4-DRAFT.tex file that will accumulate all the vcf 4.4 ideas but make it clear that this is a draft....

There are already a few PRs that cannot be merged because they are written against 4.3....

happy to discuss, or perhaps there is a better way to move this forward.

**Comment by d-cameron** [comment]
Create a v4.4 file and I'll re-raise my PRs against that baseline. I'd
prefer to call it just VCFv4.4.tex but add some big DRAFT VERSION text and
disclaimer in the document itself but I'm not too fussed either way.

**Comment by d-cameron** [comment]
Ready to close

**Comment by lbergelson** [comment]
This was done in https://github.com/samtools/hts-specs/pull/486
