### ISSUE TITLE
Explicit Denfinitions for DP and AD if Read Pairs Overlap

### ISSUE THREAD

**Issue by DarioS** [samtools/hts-specs#488]
Currently, the specification defines DP and AD in terms of "read depth", without explicitly defining what that is. When I check variants in RNA-seq data using `bcftools mpileup` in which the majority of read pairs completely overlap, I see values such as DP=30;AD=15,2,0; It appears that DP is the sum of reads whereas AD is the sum of fragments (so no double-counting redundant read of a pair). I checked if this contradicts any definition in the VCF specification, but the definition of "read" is vague.
"

**Comment by yfarjoun** [comment]
I think that this is left to the implementation, for example, should
duplicates be taken into account? what about supplementary and secondary
reads? in addition, AD might only take into account reads that definitely
support the allele in question, while DP will include "all" reads the
overlap that locus. In addition, different implementations have different
filters on reads (mapping quality, base quality etc.)

**Comment by d-cameron** [comment]
GRIDSS uses a slightly different definition for SVs. Reference depth is
reported as the number of reads aligning across the breakpoint position. If
you have 100 reads ending right before the breakpoint, and another 100
reads starting immediately after the breakpoint, your SV reference depth is
not 100, it is 0 as no read actually supports the reference allele -
they're all uninformative.

  Yossi: Do you think we should codify this approach for v4.4? I'm using
`REF` and `REFPAIR` custom fields but they're poor names for spec-defined
fields. I'll change to whatever we decide on if we want to include it.

Also to note is that reference depth is already problematic for symoblic
SVs. BND notation is fine as it's explicitly the depth at that breakend
(which will be different for the two breakends making up a breakpoint), but
the meaning of single value for the reference depth of a 300bp deletion is
ambiguous.

**Comment by yfarjoun** [comment]
I would be open to tightening the definitions a little, but not too much.
e.g. accept that different algorithms may have different filters and
preprocessing.
