### ISSUE TITLE
Proposal: Number = P (ploidy)

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [samtools/hts-specs#515]
Hi there,

I am grad student in the Gymrek Lab at UCSD. We maintain the [GangSTR](https://github.com/gymreklab/GangSTR) tandem repeat caller which generates VCFs. One of the format fields GangSTR generates is REPCN, which, for each haplotype in a call, provides the number of repeats that call represents. Currently, I believe that the VCF spec does not adequately allow for the specification of the number of such a format field, as the number may change per sample. (E.g. There would be 1 number for calls on the non-psuedoautosomal X chromosome in males, but two in females, and 1 number for calls on the Y chromosome in male, but 0 in females.)

In the current VCF spec I believe the correct thing to do is to specify `Number=.`. I would like `Number=P` to be part of the VCF spec, where P is the ploidy of the given sample. This would only be applicable for format fields, as ploidy in info fields is not well defined (see the discussion about info field ploidy in [this issue](https://github.com/samtools/hts-specs/issues/272)).

Let me know if you have any thoughts or questions. Thank you,

Jonathan

**Comment by jmarshall** [comment]
Compare the proposal in PR #442.

**Comment by LiterallyUniqueLogin** [comment]
Thank you. I searched for issues regarding ploidy, but didn't search for PRs and so didn't see this. My bad.
