### ISSUE TITLE
Reference contains IUPAC ambiguity codes but not legal in REF or ALT for VCF

### ISSUE THREAD

**Issue by mp15** [samtools/hts-specs#54]
Affects: VCF 4.2 and prior versions
The reference contains IUPAC ambiguity codes:
    $ samtools faidx ../../ref/GCA_000001405.15_GRCh38_full_analysis_set.fna chr3:16902883-16902883
    >chr3:16902883-16902883
    B

dbSNP contains IUPAC codes because the reference does for example entry rs56708014:

```
chr3    16902883    rs56708014  B   BGC .   .   RS=56708014;RSPOS=16902887;dbSNPBuildID=129;SSR=0;SAO=0;VP=0x050000080005000002000200;WGT=1;VC=DIV;INT;ASP;OTHERKG
```

However the VCF spec says: "REF - reference base(s): Each base must be one of A,C,G,T,N (case insensitive)" and for ALT "Options are base Strings made up of the bases A,C,G,T,N,*, (case insensitive) or an angle-bracketed ID String (“<ID>”) or a breakend replacement string as described in the section on breakends".  Unfortunately this conflict means that InDels or SNPs that contain ref sites with IUPAC codes are not legally representable in VCF.

**Comment by eitanbanks** [comment]
I really don't like adding IUPAC ambiguity codes to the REF.
I'm fine with pretty much any other solution.

**Comment by pd3** [comment]
For those who are not subscribed to the `vcftools-spec` mailing list, here are some of the relevant emails:
http://sourceforge.net/p/vcftools/mailman/message/34096206/
http://sourceforge.net/p/vcftools/mailman/message/34102529/
http://sourceforge.net/p/vcftools/mailman/message/34101323/

The options discussed offline and on the mailing list were these:

**How to treat ambiguity codes in the reference sequence**
1. allow IUPAC codes in REF
2. replace with N
3. replace with one of the bases, for example, R=A/G becomes A
4. both 1 or 2 are possible

**How to treat abiguity codes in ALT**
1. allow IUPAC codes in ALT
2. use symbolic alleles, such as `<R>`,`<S>`, etc

Can people +1/-1 their preferred options?

**Comment by eitanbanks** [comment]
I like options 3 (for REF) and 2 (for ALT).

**Comment by auton1** [comment]
I think allow ambiguity in the REF is asking for trouble.

I vote 3 for REF.

For ALT, I have a slight preference for 2, but don't feel very strongly
about it.


On Thu, May 21, 2015 at 9:04 AM, Eric Banks <notifications@github.com>
wrote:

> I like options 3 (for REF) and 2 (for ALT).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samtools/hts-specs/issues/54#issuecomment-104267930>.
>



-- 
Adam Auton
Assistant Professor,
Department of Genetics,
Albert Einstein College of Medicine,
1301 Morris Park Avenue,
Price Center, Room 353B,
Bronx, New York 10461

Tel: +1 (718) 678 1150

**Comment by vadimzalunin** [comment]
+1 to option 2: replace with N

**Comment by cyenyxe** [comment]
I find point 1.4.1.4 a bit confusing from a tool developer perspective. When it states that IUPAC codes in the REF could be "reduced", does that mean that tools should still accept them and run the transformation themselves? Otherwise, being the file authors responsibility, it could be described like: 

> IUPAC ambiguity codes in the reference sequence must be reduced to a concrete base by using
> the one that is first alphabetically (thus R=A/G as a reference base is converted to A in VCF.)

**Comment by pd3** [comment]
@cyenyxe You are right, "must be reduced" is what I meant. Thank you.

**Comment by sjackman** [comment]
I've just run into this issue myself. My assembled genome of short reads has 9 sites with ambiguity codes. When I align the reads to the reference, it's clear what the true base should be. When I call variants using `bcftools call -c --ploidy=1 -Oz` these variants sites are not output by `bcftools`.

I'm okay with either the convert to `N` or convert to the first alphabetical nucleotide of the ambiguity code. My preference is to convert to `N`.
