### ISSUE TITLE
Clarify the validity of BND as first-level symbolic alleles

### ISSUE THREAD

**Issue by tskir** [samtools/hts-specs#546]
Raised as [part of discussions](https://github.com/samtools/hts-specs/pull/465/files#r371978302) in #465

@cwhelan
> Is `<BND>` a valid first-level symbolic alt (which I think this language implies) according to this PR, or do breakend alts need to be written in the detailed format with square brackets, etc?

@thefferon
> @d-cameron may best be able to speak to this, but it is my understanding that the intention when using SVTYPE=BND is that the ALT column always contain the bracketed notation, e.g., "**]5:7576543]G**". @cwhelan, can you provide an (hypothetical) example of a variant in which SVTYPE=BND and ALT=<BND>? I am not sure what that would look like.

> The notion of an alt of <BND> does bring me to a related subject I wanted to raise – but rather than add another topic to this PR, I'll open a new issue and reference it here.

@cwhelan
> I'm not suggesting that it should be allowed (although this is something the current release of gnomAD does; I'm working to fix that for future releases right now); just trying to point out that unless I'm misreading something in the language in this PR, the specification would seem to allow it even after these changes are merged.

**Comment by tskir** [comment]
Also a [comment](https://github.com/samtools/hts-specs/pull/468#discussion_r374322198) by @cwhelan:

> I'd clarify whether it's required to include `SVLEN` for `BND` records, and also explicitly state what `SVLEN` should be for intra-chromosomal `BND` records.

**Comment by d-cameron** [comment]
>I'd clarify whether it's required to include SVLEN for BND records, and also explicitly state what SVLEN should be for intra-chromosomal BND records.

Already done as part of #468

**Comment by d-cameron** [comment]
`<BND>` should not be a valid ALT allele.

**Comment by d-cameron** [comment]
Fixed in 4.4
