### ISSUE TITLE
vcf: § 6.3.1 Site encoding: QUAL field is misplaced

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#557]
In VCFv4.3 § 6.3.1, the `QUAL` field is misplaced. The field should be after `rlen`, not `n_fmt_sample`. The correct order can be verified with the example under "Putting it all together" and the implementation in [htslib/vcf.c#L1245](https://github.com/samtools/htslib/blob/bd133acf51498431a5c7dfd8aa06ce17ec6d3b96/vcf.c#L1245).

This affects `VCFv4.1.tex`, `VCFv4.2.tex`, `VCFv4.3.tex`, and `VCFv4.4.draft.tex`. (The tables in `VCFv4.1.tex` and `VCFv4.2.tex` are broken.)

**Comment by daviesrob** [comment]
See pull request #456, which will fix this when merged.

**Comment by zaeleus** [comment]
Closed by #456. See #567 for the remaining issues in the BCF section.
