### ISSUE TITLE
test/cram: 0000_empty_noeof.cram is not valid

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#561]
[CRAMv3.0 § 9 End of file container](https://samtools.github.io/hts-specs/CRAMv3.pdf#End%20of%20file%20container) states a final EOF container is required:

> A special container is used to mark the end of a file or stream. It is required in version 3 or later.

Therefore, [`test/cram/3.0/passed/0000_empty_noeof.cram`](https://github.com/samtools/hts-specs/blob/64c8759705ada74196198c4ff95ce23a1ec3b3e5/test/cram/3.0/passed/0000_empty_noeof.cram) should not be considered a valid CRAMv3 file.

**Comment by jkbonfield** [comment]
That's a good point and thanks for raising it.  I'd forgotten that we labelled it as required rather than simply a recommended feature as it is in BAM.

Yes it should be moved out of "passed" then.
