### ISSUE TITLE
test/sam/passed: Multiple files have invalid headers

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#563]
4 test SAM files marked as passed have invalid headers because some comment (`@CO`) lines are not tab-delimited:

  * `test/sam/passed/pnext.pair-2nd.sam`
  * `test/sam/passed/pnext.pair-supp.sam`
  * `test/sam/passed/pnext.warn-pair-2nd.sam`
  * `test/sam/passed/pnext.warn-pair-supp.sam`

```
$ samtools view --no-PG test/sam/passed/pnext.pair-2nd.sam
[E::sam_hrecs_error] Missing tab at line 11: "@CO     xx        11        21        31        41"
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 17
samtools view: error reading file "test/sam/passed/pnext.pair-2nd.sam"

$ samtools view --no-PG test/sam/passed/pnext.pair-supp.sam
[E::sam_hrecs_error] Missing tab at line 9: "@CO     11        21   25   31   35   41"
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 13
samtools view: error reading file "test/sam/passed/pnext.pair-supp.sam"

$ samtools view --no-PG test/sam/passed/pnext.warn-pair-2nd.sam
[E::sam_hrecs_error] Missing tab at line 12: "@CO     xx        11        21        31        41"
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 18
samtools view: error reading file "test/sam/passed/pnext.warn-pair-2nd.sam"

$ samtools view --no-PG test/sam/passed/pnext.warn-pair-supp.sam
[E::sam_hrecs_error] Missing tab at line 9: "@CO     11        21   25   31   35   41"
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 13
samtools view: error reading file "test/sam/passed/pnext.warn-pair-supp.sam"
```

**Comment by jkbonfield** [comment]
The irony of adding a proper header parser later than writing the test data. :-)

Thanks for this report.

**Comment by jmarshall** [comment]
Oops :smile:

Unfortunately none of us ran these files through `picard ValidateSamFile` either, which would have detected this problem at the time they were written.

ValidateSamFile also detects some semantic issues with some of these files, e.g., for _pnext.pair-2nd.sam_:

```
ERROR::INVALID_ALIGNMENT_START:Record 3, Read name a1, Alignment start (111) must be <= reference sequence length (100) on reference yy
```

along with its usual more overreaching policy-based complaints about missing read groups, etc.

At some point we should run all these test files through ValidateSamFile and fix any such significant semantic issues.

**Comment by jkbonfield** [comment]
Good point.  Although some semantic issues raised by both picard and samtools are legal SAM.  It becomes questionable where the format ends and "sense" starts.  Eg a mapping quality existing for an unmapped read is legal, but stated as having no meaning IIRC.
