### ISSUE TITLE
Switch from `rerun.sh` to `latexmk`

### ISSUE THREAD

**Issue by michaelmhoffman** [samtools/hts-specs#569]
The `latexmk` command that comes with TeX Live seems to fulfill the same purpose as `rerun.sh` and is robust to a lot more edge cases, and probably quite a bit more future-proof.

**Comment by michaelmhoffman** [comment]
For example, `rerun.sh` does not seem to rerun TeX enough times for the acronym package to work.

**Comment by jmarshall** [comment]
Various maintainers have been reluctant to use `latexmk` in the past, because they did not have it installed. It may well be time to revisit this… 🤷

Starting from an empty `new/` directory, both `rerun.sh` and `latexmk` run latex the same number of times (namely 3) and produce the same acronym-related warnings on the final run:

```
LaTeX Warning: Hyper reference `acro:ASCII' on page 6 undefined on input line 374.
LaTeX Warning: Hyper reference `acro:ASCII' on page 6 undefined on input line 374.
LaTeX Warning: Hyper reference `acro:regex' on page 6 undefined on input line 377.
LaTeX Warning: Hyper reference `acro:regex' on page 6 undefined on input line 377.
```

Is this what you're seeing, or do you experience a scenario in which `rerun.sh` and `latexmk` produce different results?

I suspect those warnings are some unfortunate interplay between hyperrefs and acronym commands…

**Comment by michaelmhoffman** [comment]
After reverting commit c773dcf93830b05d38b21e6f65887c9d07a49d17 to restore the `changepage` package (in an incorrect attempt to get this working on the CircleCI system that doesn't have `changepage`), `rerun.sh` is now working for me. I don't know why it wasn't working before—it's probably either because I was using it correctly or something else.

Will figure out how to remove those warnings for #570.

I'd still suggest using `latexmk` for the reasons above but it might not be a blocker for #570.

**Comment by jkbonfield** [comment]
FYI latexmk seems to work for me, assuming I used it correctly.  Is there a specific document which you need comparing?

**Comment by michaelmhoffman** [comment]
If you do this, you will also need to remove `new/*.fls` and `new/*.fdb_latexmk` as part of the `mostlyclean` target, as done in #570.

**Comment by jmarshall** [comment]
Assuming there are no maintainers or contributors who still do not have access to `latexmk`, there is really no good reason not to be using it, as it's the standard well-known tool for this job.

So a good way forward would be to make the `s/rerun.sh/latexmk/` change in _Makefile_, ignore and clean those additional files as recommended, but leave the `rerun.sh` script in place in the repo in case anyone needs to continue to use it.

**Comment by jkbonfield** [comment]
Can I suggest having the rerun.sh command line as a comment in the Makefile too, so we can trivially comment out latexmk and uncomment rerun.sh should we ever be in a situation of needing it.  As time goes by we'll get more confident as to whether anyone still requires it.
