### ISSUE TITLE
Significance of the ordering of tagged fields in header lines

### ISSUE THREAD

**Issue by Unaimend** [samtools/hts-specs#571]
So I'd like to know if the header tags in some predefined order.
According to my understanding this would be a valid headerline.
`@HD VN:1.6 SO:coordinate`
But when I switch around the tags, would this still be valid?
`@HD  SO:coordinate VN:1.6`

**Comment by jmarshall** [comment]
The order of the header tagged fields is not significant. Whatever order they appear in, the meaning is the same; and any order for the tagged fields is valid.

The specification (§1.3, “The header section”) currently does not say anything about this (hence you can assume that this means no particular ordering is invalid). I have some upcoming clarifications to make in this section, so I'll also add some wording to make this insignificance of the ordering explicit.

**Comment by Unaimend** [comment]
Thank you for the clarificarion
