### ISSUE TITLE
csi: Unused `bin_limit` parameter: `min_shift`

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#573]
In `CSIv1.pdf`, the `bin_limit` function has an unused `min_shift` parameter. The body only uses `depth`.

> ```
> int bin_limit(int min_shift, int depth)
> {
>     return ((1 << (depth+1)*3) - 1) / 7;
> }
> ```

The function is also called with a `min_shift` argument earlier.

> In CSI, the pseudo-bins have bin number `bin_limit(min_shift, depth) + 1`.

**Comment by jmarshall** [comment]
Yes.

The pseudocode function `bin_limit()` is presented in terms of the two CSI parameters `min_shift` and `depth`, similarly to the other two functions. But the number of bins depends only on the depth (not on the width (in coordinates)), so `min_shift` is unused.
