### ISSUE TITLE
VCF: Clarify GL Genotype Field Ordering

### ISSUE THREAD

**Issue by adamnovak** [samtools/hts-specs#58]
The description of the GL field says that:

    If A is the allele in REF and B,C,... are the alleles as ordered in ALT, the ordering of genotypes for the likelihoods is given by: F(j/k) = (k*(k+1)/2)+j.

It is unclear to me how one is supposed to interpret this equation as defining an ordering of anything. What do `j` and `k` represent? Why are we dividing one by the other? What does the value returned by the `F` function represent?

I *think* what is happening is that `j` represents the number of the first allele of a diploid pair (with 0 for the ref allele) `k` represents the number of the second, the "/" is really denoting that the argument of the function is the unphased genotype composed from those two alleles, and the result of the function is the index in the GL array at which the likelihood of that genotype is to be found. If that is the case, this should be described more clearly in the spec. If that is *not* the case, this should *definitely* be described more clearly in the spec.

Furthermore, for triploid or higher sites, the spec merely says genotype likelihoods should appear in "the canonical order". What order is that, exactly?

**Comment by atks** [comment]
The below wiki explains the ordering of genotypes given ploidy and alleles in the general case.

http://genome.sph.umich.edu/wiki/Relationship_between_Ploidy,_Alleles_and_Genotypes
