### ISSUE TITLE
Providing information about old versions of htsget

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#585]
We are now up to htsget 1.3.0, and <https://samtools.github.io/hts-specs/> does not (currently) provide direct access to earlier versions of the specification. Implementors may need to know what has changed between different versions of the protocol; for example, maintainers of a server written in the 1.2.0 era may need to know what capabilities were part of the protocol at that time and what is new that they should consider adding.

Such readers always have the option of spelunking around in the git history to find the exact specification text from earlier days, but this is not especially convenient. There are essentially two ways to provide convenient access to this information:

* Designate a commit for each older specification version to be considered “canonical for [e.g.] 1.2.0” and make them available at another URL with a version number in it.

* Maintain an appendix in the current specification listing the significant changes between versions. (See e.g. the respective appendices of [SAMv1.pdf](https://samtools.github.io/hts-specs/SAMv1.pdf) and [SAMtags.pdf](https://samtools.github.io/hts-specs/SAMtags.pdf).)

IMHO the latter is preferable: it provides all the information that most readers need, without multiplying the number of documents that we need to maintain or make available, and does not ask readers to study multiple documents and figure out the differences between them themselves.

As a first approximation, here are the significant additions in each of our htsget versions to date:

1.3.0 POST requests
1.2.1 service-info endpoint
1.2.0 header requests and `class` attributes
1.1.1 `referenceName=*` to request unmapped reads
1.1.0 variants endpoint
1.0.0 first promulgated version

**Comment by jkbonfield** [comment]
You list two possible solutions, with the 2nd being preferable (I agree btw as knowing what changed is more useful than simply having a copy and requiring people to diff it themselves), but I wonder if it's possible to do both.  Htsget is MarkDown so it doesn't need anything fancy to view it, just a URL.  The version history at the end could therefore contain direct links to the repository commits containing the earlier versions.

Eg.

[1.2.1](https://github.com/samtools/hts-specs/blob/33dbb910e77b9cb4d8c5c2d6580edbf7020067d0/htsget.md) service-info endpoint

It's possible we could do the same with SAM etc, but it'd mean linking to a PDF URL which may not be so useful.

**Comment by jmarshall** [comment]
The canonical version of the htsget spec is the GH Pages-rendered one at <http://samtools.github.io/hts-specs/htsget.html> so we'd have to cause the text from old commits to be rendered to be able to point at web-rendered versions.

However _htsget.md_ is written in the common subset of kramdown (for the web rendering) and GFM (for the repository view; the main area to be careful of the differences is tables), so pointing at URLs within the GitHub repository view (as your example does) gives a rendering that doesn't lose very much fidelity. So it's simple enough to do and probably worthwhile.

A draft appendix is now PR #586.

**Comment by jkbonfield** [comment]
I wasn't aware of subtleties in markdown versions, but it's a cheap win.  Thanks.

**Comment by jmarshall** [comment]
The version appendix has been merged as drafted. Reopening this so we don't forget about adding links as suggested by @jkbonfield.
