### ISSUE TITLE
REF column always a single base for breakends (i.e. SVTYPE=BND)?

### ISSUE THREAD

**Issue by eroller** [samtools/hts-specs#588]
The current spec specifies that the REF field of a breakend record indicates a base or sequence of bases, as in all VCF records:

https://github.com/samtools/hts-specs/blob/0bc6afe94bdc2ffb1015b5747ada41ad60d8b4ed/VCFv4.4.draft.tex#L1022

I'm wondering if it even makes sense for REF to be anything but a single base. If not, should the spec be updated to make that explicit?  If a sequence of bases is allowed there aren't any examples of it in the spec (as far as I can tell), so how would that be interpreted in the context of the 4 different possible forms of ALT?

**Comment by jkbonfield** [comment]
> In practice it's a terrible idea and I hope nobody actually creates vcfs like this. Worst case, I'll just normalise it when I see it in any of my pipelines.

If we think it's a terrible idea, then is it something to consider tightening up for VCF v4.4?

**Comment by jkbonfield** [comment]
We just discussed this again in our meeting and concluded that there doesn't really need to be a change to the specification.  While it's not necessarily a good idea to use multiple bases as practically speaking it's challenging to work with, it is permitted and there's little desire to go back and disallow this.

So I'm closing the issue.

(Thank you for raising it though.)
