### ISSUE TITLE
VCF: Ambiguity in ##contig specification

### ISSUE THREAD

**Issue by cyenyxe** [samtools/hts-specs#60]
The meta "contig" field format is specified as:

> As with chromosomal sequences it is highly recommended (but not required) that the header include tags describing the contigs referred to in the VCF file. This furthermore allows these contigs to come from different files. The format is identical to that of a reference sequence, but with an additional URL tag to indicate where that sequence can be found. For example:
>
> `##contig=<ID=ctg1,URL=ftp://somewhere.org/assembly.fa,...>`

But all the examples follow this format:

`##contig=<ID=20,length=62435964,assembly=B36,md5=f126cdf8a6e0c7f379d618ff66beb2da,species="Homo sapiens">`

From the first paragraph, one would infer that the contig is optional, but the rest is quite ambiguous. Could you please clarify the following and, if possible, include the answers in the next version of the spec?

* Whether the ellipsis after URL represents "whatever you want"
* Whether URL is optional
* Whether the "long style" (length, assembly, md5, species) is a replacement for just the URL

**Comment by pd3** [comment]
Hi, all attributes are optional, except for ID.

**Comment by cyenyxe** [comment]
Thank you very much for your fast reply :)

Wouldn't it be nice to be a bit less flexible when specifying a contig, so its information can be retrieved by potentially any VCF processing tool? Otherwise every team will need an ad hoc parser that knows how contig are described in their specific case. 

As an example, I am contributing to the EBI variant archive (http://www.ebi.ac.uk/eva/?Home), which accepts "any" VCF submission, and without these constraints it is impossible for us to validate and store contigs information in a well-structured, useful way. If "assembly" and "species" were mandatory, we would be able check and validate the samples mapped against which assembly. URL could be still optional, and a nice addition for those that want to facilitate the associated FASTA file.

**Comment by pd3** [comment]
I see how convenient it would be to require these attributes for the archive. Unfortunately, for different applications different attributes are considered essential, users generally disagree what is the bare minimum which should be required. 
The archive could perhaps require that it accepts only VCF with "assembly" and "species" specified and check that as part of the validation process? There are tools to reheader VCFs easily - `bcftools reheader`.

**Comment by cyenyxe** [comment]
Yes, I guess that will be the only option. Thank you.
