### ISSUE TITLE
[VCF/BCF] Specify whether multiple unstructured header lines with the same ID are allowed

### ISSUE THREAD

**Issue by andersleung** [samtools/hts-specs#602]
The VCF/BCF spec mentions that structured header lines must have a unique ID in their type, but it does not say whether this is the case for unstructured header lines (ones of the form `##id=content`). This issue comes up for example when processing a file in multiple stages with a tool that records its command line input as an unstructured header line. Some clarification from the spec maintainers on this issue would be appreciated.

@cmnbroad

**Comment by pd3** [comment]
Unstructured header lines are not required to have a unique id. For example you could add multiple `#comment=` lines etc.

**Comment by jkbonfield** [comment]
Closing as answered, but this is related to #608 which also covers the language describing unstructured headers.
