### ISSUE TITLE
Add support for supplementary alignment flag in CRAM3

### ISSUE THREAD

**Issue by vadimzalunin** [samtools/hts-specs#61]

**Comment by jmarshall** [comment]
@vadimzalunin @jkbonfield: @yfarjoun points out that the CRAM v3 spec (_§CRAM record bit flags_) still does not list 0x800 SUPPLEMENTARY.  Is this an oversight, or is there a reason for this?

I've been vaguely assuming that, as for alignment record auxiliary tags, the intention was that CRAM effectively includes SAM/BAM's FLAG bits by reference.  In that case, adding 0x800 here is just a minor editorial fix; or are there further considerations (w.r.t. chains of read pairs or similar) that need to be taken into account?

**Comment by jmarshall** [comment]
Ping…

**Comment by jmarshall** [comment]
Ping…

**Comment by jkbonfield** [comment]
It's been kicking around long enough and I see no reason for it, so I just fixed it. :-)
