### ISSUE TITLE
SAM tag array types

### ISSUE THREAD

**Issue by marcus1487** [samtools/hts-specs#610]
SAM format tags allow arrays via the `B` type, but I am not able to find a specification of the single letter codes indicating the type of an array. From the optional tags page 3 different types are used. The `CG` tag uses type `I` which appears to be a long int (32 bit int; maybe unsigned). The `FZ` tag uses the `S` type (this type is not clear to me). Finally the `ML` tag uses the `B` type to indicate a byte type (8-bit unsigned int).

It would be good to add to the spec (and just know in a response here) a list of all the single letter codes available for custom array tag types.

**Comment by jmarshall** [comment]
_SAMtags.pdf_, which lists the semantics of numerous pre-defined tags, is a companion to _SAMv1.pdf_, which describes the syntax and representation of SAM and BAM files.

The `B` array types are described in _SAMv1.pdf_ §1.5 (“[…] Optional fields”) for SAM and §4.2.4 (“Auxiliary data encoding”) for BAM.

**Comment by marcus1487** [comment]
Thanks so much @jmarshall . Not sure how I missed the snippet. 

For those that might stumble upon this post, here is the relevant text for which I was searching: "For an integer or numeric array (type ‘B’), the first letter indicates the type of numbers in the following comma separated array. The letter can be one of ‘cCsSiIf’, corresponding to int8 t (signed 8-bit integer), uint8 t (unsigned 8-bit integer), int16 t, uint16 t, int32 t, uint32 t and float, respectively."
