### ISSUE TITLE
Status of CRAM Beta<byte> encoding

### ISSUE THREAD

**Issue by cmnbroad** [samtools/hts-specs#627]
We're doing some cross validation of htsjdk CRAM using the files in https://github.com/samtools/hts-specs/tree/master/test/cram/3.0. The htsjdk implementation of the Beta encoding only supports integer values (section 13.5 of the CRAM spec says that the Beta encoding is for integer only, which seems to up match the table at the beginning of Section 13).

The file `1101_BETA.cram` in the test uses a Beta encoding for byte values. I'm not sure if we should update the spec or the implementation. Is the intent that Beta should work for byte values ?

On a related note, does the presence of a test file in the "passed" folder imply that the file is believed to be spec compliant ?

**Comment by jkbonfield** [comment]
Thanks for reporting this.  I'll need to check whether we actually produce them and they exist in the wild, or whether that was some forcibly produced data for testing purposes.  If the latter we should just fix the test data.  If they exist in the wild then we probably should just relax the spec a bit (as we did with TN/TC leakage from 1.0), for practicality reasons.

Yes, passed is meant to mean valid data.  However it's not the first case we've spotted of invalid data creeping in.  The lack of any prior validation suite has meant things slip by.

**Comment by jkbonfield** [comment]
It appears the tightening of the language describing the data types per encoding arrived at some point in CRAM 3.0 tex.  The CRAM 2.1 spec just uses the word "number", which is somewhat vague and it's debateable whether a byte could be considered as a number.  In 3.0, the only byte series are characters (names, bases, codecs) apart from quality scores.

Older htslib and scramble releases uses BETA more, but now it's very restricted and only used from what I can see (and possibly that should be culled) for *unsorted* positional data.   Much earlier releases could emit huffman or beta for many more fields.  While the code didn't distinguish between types of integer vs beta, the selection was always done on number of distinct values and <200 selected huffman.  It's not possible to get >=200 for any of the data series listed as byte except possibly for MQ (in 2.1, it's integer in 3.0, and maybe it was in 2.1 in reality if not specified as such?).

Therefore realistically, I think we're safe in the assertion that beta cannot occur in the wild for any byte data series from htslib or scramble, and I assume also not for htsjdk given this issue.  Therefore I think fixing the test file is probably the best solution.

**Comment by jkbonfield** [comment]
Can you please test the new 1101_BETA.cram from #628 and see whether it works with your latest implementation please?  If so we can merge it.

Thanks for the bug report.

**Comment by cmnbroad** [comment]
@jkbonfield The new file seems to work fine with htsjdk. Thanks for the quick turnaround.
