### ISSUE TITLE
cram: Mapped/unmapped reads pseudocode references nonexistent preservation map field

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#635]
This is regarding [_CRAM format specification (version 3.0)_](https://github.com/samtools/hts-specs/blob/ef58a8c058a06585c81bb33470b1dcaabd5a8f91/CRAMv3.pdf) (2021-10-15).

In § 10.6 "Mapped reads" and § 10.7 "Unmapped reads", the psuedocode references a "preserve quality scores" flag in the preservation map, i.e., `container_pmap.preserve_quality_scores`.

https://github.com/samtools/hts-specs/blob/ef58a8c058a06585c81bb33470b1dcaabd5a8f91/CRAMv3.tex#L1632
https://github.com/samtools/hts-specs/blob/ef58a8c058a06585c81bb33470b1dcaabd5a8f91/CRAMv3.tex#L1694

The preservation map does not define such a field (see § 8.3 "Compression header block").

These should be `CF AND 1`, referring to the "quality scores stored as array" (`0x1`) CRAM bit flag described in § 10.1 "CRAM record".

**Comment by jkbonfield** [comment]
Yes you are correct.  I tracked it back to the initial cram/cram.tex checkin here and it's always been `CF&1`.  That's obviously just my error when writing the pseudocode.

Thanks for spotting and reporting this.  Bit by bit with extra eyes looking at the spec it's improving.  Most appreciated and I'll make a PR to fix it.
