### ISSUE TITLE
1-1 correspondence for ploidy greater than 2.

### ISSUE THREAD

**Issue by atks** [samtools/hts-specs#64]
For ploidy 2, the VCF specification gives the ordering F(j/k) = (k*(k+1)/2)+j.  This works for any number of alleles as long as ploidy is 2.

Is there a suggested ordering for variants where the number of alleles is less than the ploidy?  Say ploidy = 5 and n_allele = 3?

**Comment by pd3** [comment]
The explanation was improved in the VCFv4.3 draft (http://samtools.github.io/hts-specs)

**Comment by atks** [comment]
I think it should print a_p ... a_1

else it will generate for P=2, A=2
AA
BA
BB

and for P=3, A=3
AAA
BAA
BBA
BBB
CAA
CBA
CBB
CCA
CCB
CCC

**Comment by pd3** [comment]
We are interested in the order of genotypes, not about phasing. AA,AB,BB is the same as AA,BA,BB.

**Comment by atks** [comment]
ok.

Do you know of a known function to map a genotype like A/C/C, given no. of alleles and ploidy directly to its order without iterating the entire sequence?

**Comment by pd3** [comment]
binom(N+p-1)(p), I think

**Comment by atks** [comment]
I think this works.
http://genome.sph.umich.edu/wiki/Relationship_between_Ploidy,_Alleles_and_Genotypes

**Comment by pd3** [comment]
Yeap, that's the same then. Thanks for checking.

**Comment by atks** [comment]
So just to close it.  I was referring to getting the index of an observed genotype so that I can perform random access.

//number of genotypes given P and A where P = ploidy, A= no. of alleles
F(A,P) = \binom{P+A-1}{A-1}

//indexing from a_1 ... A_P where a_i are the ordered observed alleles iencoded from 0 to A-1
G(a_1,.. , a_P) =    a_1      when  P=1 
G(a_1,.. , a_P) =    F(P, a_P) + G(a_1, ..., a_P-1)  when P!=1
