### ISSUE TITLE
VCF bundle information isn't stored anywhere

### ISSUE THREAD

**Issue by adamnovak** [samtools/hts-specs#643]
The "Phasing adjacencies in an aneuploid context" section of the VCF spec defines "bundles" for describing the phasing through breakends. They are given a notation with a '>' separator: 

https://github.com/samtools/hts-specs/blob/3a17aaf64515b51023b29267fb69833f31adfaee/VCFv4.4.draft.tex#L1543

The numbers reference the `HAP` field defined here:

https://github.com/samtools/hts-specs/blob/3a17aaf64515b51023b29267fb69833f31adfaee/VCFv4.4.draft.tex#L807

But no FORMAT field for actually storing the bundles is defined in the spec document, and no example of a VCF describing bundles is given. Going by [this initial proposal](https://sourceforge.net/p/vcftools/mailman/attachment/4D75E14E.9070609%40soe.ucsc.edu/1/) it was supposed to be:

```
##FORMAT=<ID=BHP,Number=G,Type=String,Description="Bundle Phase Set ">
```

While [this example from PyVCF](https://github.com/jamescasbon/PyVCF/blob/476169cd457ba0caa6b998b301a4d91e975251d9/vcf/test/example-4.1-bnd.vcf#L19) has it as:

```
##FORMAT=<ID=BHAP,Number=G,Type=String,Description="Bundle Phase Set ">
```

The spec needs to include one or the other of these (or something else?) to describe where bundle information is meant to be stored. It should also include an example.

**Comment by d-cameron** [comment]
This has now been clarified in the VCFv4.4 draft specifications.
