### ISSUE TITLE
cram: Define container header fields for the header container

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#645]
This is regarding [_CRAM format specification (version 3.0)_](https://github.com/samtools/hts-specs/blob/3a17aaf64515b51023b29267fb69833f31adfaee/CRAMv3.pdf) (2022-04-12).

Recently, an extra description was added to § 7 "Container header structure" describing the alignment start and span fields depending on the reference sequence ID (https://github.com/samtools/hts-specs/commit/132abaf2e011d15b42975bde377bbf37feb285b0). This focuses on data containers but omits discussion about the CRAM header container. The following table shows that different writers emit different combinations of values for the header container.

| library                 | reference sequence ID | alignment start | alignment span | example               |
|-------------------------|----------------------:|----------------:|---------------:|-----------------------|
| [HTSJDK < 2.22.0]       |                     0 |              -1 |              0 | [1301_slice_aux.cram] |
| [HTSJDK >= 2.22.0]      |                    -1 |               0 |              0 | N/A                   |
| [HTSlib] (as of 1.15.1) |                     0 |               0 |              0 | [0100_header1.cram]   |

Like the EOF container, the header container is a special case, but unlike the EOF container, the header container's header is undefined (and unintuitive, given the three cases above). There should be a more thorough description and a set of values defined to avoid this ambiguity.

[HTSJDK < 2.22.0]: https://github.com/samtools/htsjdk/blob/5445b9081a057253b66ed15566bba1e1854202e8/src/main/java/htsjdk/samtools/cram/build/CramIO.java#L272
[1301_slice_aux.cram]: https://github.com/samtools/hts-specs/blob/3a17aaf64515b51023b29267fb69833f31adfaee/test/cram/3.0/passed/1301_slice_aux.cram
[HTSJDK >= 2.22.0]: https://github.com/samtools/htsjdk/blob/f461401e38fe95362a6d3c5afd8b592964b4bd29/src/main/java/htsjdk/samtools/cram/structure/ContainerHeader.java#L153-L154
[HTSlib]: https://github.com/samtools/htslib/blob/3c44c0b9eabcb1f6e111ec1b94e287155085e523/cram/cram_io.c#L4884
[0100_header1.cram]: https://github.com/samtools/hts-specs/blob/3a17aaf64515b51023b29267fb69833f31adfaee/test/cram/3.0/passed/0100_header1.cram

**Comment by jkbonfield** [comment]
Good spot.

I think this is probably just a case of no one noticing because none of the fields have any meaning in this context so all implementations simply discarded them after decode.  It feels like the correct language would be to explicitly state that the fields must be present, but have no meaning so can be ignored after decode.
