### ISSUE TITLE
Further clarify the INFO/END key for structural variants.

### ISSUE THREAD

**Issue by DonFreed** [samtools/hts-specs#647]
In section 3, the v4.4 spec currently has:
> For precise variants, END is POS + length of REF allele − 1, and the for imprecise variants the corresponding best estimate.

However, this is somewhat contradicted by the earlier description of this field in section 1.6.1:
> END: End reference position (1-based), indicating the variant spans positions POS–END on reference/contig CHROM. Normally this is the position of the last base in the REF allele, so it can be derived from POS and the length of REF, and no END INFO field is needed. However when symbolic alleles are used, e.g. in gVCF or structural variants, an explicit END INFO field provides variant span information that is otherwise unknown.

This discrepancy caused some confusion when interpreting symbolic `<DUP>` alleles in our VCF evaluation tool, https://github.com/Sentieon/hap-eval/issues/1.

I am hoping that the spec could be amended so that sections 1.6.1 and 3 are consistent and ideally provide some additional guidance on setting the INFO/END field for different symbolic alleles.

This is related to many previous issues, e.g. #134, #640, [comment in #173](https://github.com/samtools/hts-specs/issues/173#issuecomment-465245604). A comment [in #266](https://github.com/samtools/hts-specs/pull/266#discussion_r284527053), suggests that INFO/END should be disallowed for BNDs, although I'm not sure where this is mentioned in the spec.

**Comment by d-cameron** [comment]
Thanks for the feedback. It looks like there were a few `END` statements that I missed in the 4.4 drafts. The intent for 4.4 is to deprecate `END` for symbolic SV events in favour of `SVLEN`. S3 needs updating to explicitly specify how `END` works for symbolic alleles (particularly gVCF).

**Comment by d-cameron** [comment]
> This would cause tandem duplications to have different overlap intervals depending on whether they are described as a (left-shifted) precise variant or a symbolic `<DUP>` allele.

How do you mean? Take the following example:
```
12345 ref coordinate
ACGTA ref
ACGTGTA dup (GT)
```

Doesn't left-alignment turn this into pos=2 REF=C ALT=CGT which matches the POS-at-based-preceding-the-SV interpretation (POS=2, REF=C, ALT=<DUP>, SVLEN=2)?

**Comment by DonFreed** [comment]
Agreed that both the left-alignment (precise) representation and the symbolic representation can be used to describe the same event (pos=2 REF=C ALT=CGT *and* POS=2, REF=C, ALT=, SVLEN=2 are identical). I'm wondering if there's some consensus regarding whether `bcftools query <chrom>:3-` should retrieve the symbolic allele (it seems like this is the intention)?

Here's a fully-worked example with three different records describing the 2bp insertion from your example:
```
##fileformat=VCFv4.3
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=SVLEN,Number=.,Type=Integer,Description="Difference in length between REF and ALT alleles">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##contig=<ID=chr1,length=248956422>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample
chr1    2       .       C       CGT     50      .       .       GT      0/1
chr1    2       .       C       <DUP>   50      .       SVLEN=2 GT      0/1
chr1    2       .       C       <DUP>   50      .       SVLEN=2;END=4   GT      0/1
```

With bcftools v1.15.1, `bcftools query chr1:3-` retrieves the last record (due to the special interpretation of INFO/END from #425).

**Comment by d-cameron** [comment]
Indexed retrieval should work the same way whether a symoblic SV has an implicit or explicit `END` position written. That said, indexing is technically out of scope of the VCF specifications themselves so actual behaviour is up to the implementation. The latest round of 4.4 changes does include text explicitly stating what `END` is for each type of record but it doesn't specify whether SVLEN, END, either, or both need to be written for symbolic SVs. Considerations are:

- SVLEN: breaks backwards compatibility; some popular callers only write END
- END: still need SVLEN when there are multiple symoblic SV ALT alleles
- Either: SVLEN needs to take precedence over SVLEN. Annoying for symoblic SV parser but they need to do this anyway to be able to parse pre-4.4 VCFs.
- Both: simplest for indexing, potential for data inconsistency.
