### ISSUE TITLE
Questions raised by the proposed VCFv4.3 encoding changes

### ISSUE THREAD

**Issue by bioinformed** [samtools/hts-specs#65]
I'm in favor of the change to make VCF encoding UTF-8 and to add URL/percent encoding of INFO and FORMAT values.  However, these changes do raise some practical issues:

1. UTF-8 encoding is not propagated to BCF.  The draft spec continues to refer to ASCII encoded strings, which would require application of percent coding to store UTF-8 strings.  The definition of Character still states that, "[a]s with Strings, UNICODE characters are not supported." Should the definition of scalar Character encoding be changed to support code points < 127 and String encoding be changed to unrestricted UTF-8?

2. URL/percent coding is defined in multiple standards, some only supporting ASCII, some any 8-bit character set, and different versions for UTF-8 and other multi-byte encodings.  It would be helpful if the specs referred to a specific standard for URL/percent coding (e.g. RFC 3986 or the variant that encodes higher code points as  %uxxxx as in ECMA-262).

**Comment by pd3** [comment]
I am closing this issue, as it is covered also by #89
