### ISSUE TITLE
Re "Representing variation in VCF records", multiallelic variants and haplotypes

### ISSUE THREAD

**Issue by dakl** [samtools/hts-specs#66]
Hi, 

I've a question about the examples in the VCF 4.2 spec (same as in 4.1 I think). The first example is

```
#CHROM POS ID REF ALT QUAL FILTER INFO 
20  3   .   C   G   .   PASS    DP=100 
20  2   .   TC  T   .   PASS    DP=100 
20  2   .   TC  TCA .   PASS    DP=100
```

The third variant here (20:2 TC->TCA) seems to me to be better repesented as 

```
20  3   .   C  CA .   PASS    DP=100
```

since the ref base T as 20:2 doesn't change. The minimal common denominator is the `C` at `20:3`. 

The next example

```
#CHROM POS ID REF ALT QUAL FILTER INFO
20  2   .   TC  TG,T    .   PASS    DP=100
```

Could (should?) be represented as two variants

```
#CHROM POS ID REF ALT QUAL FILTER INFO
20  2   .   TC  T    .   PASS    DP=100 ## deletetion of C
20  3   .   C  G    .   PASS    DP=100 ## SNP C->G
```

The complex example

```
#CHROM POS ID REF ALT QUAL FILTER INFO
20  2   .   TCG TG,T,TCAG   .   PASS    DP=100
```

would then be

```
#CHROM POS ID REF ALT QUAL FILTER INFO
20  2   .   TCG TG,T   .   PASS    DP=100 ## the deletions
20  3   .   C   CA  .   PASS    DP=100 ## insertion of A at after the C at 20:3
```

The common theme to these changes is to evaluate each alt allele with the ref separately to determine the POS of that allele. REF/ALT are then trimmed to the minimal common base. This means that matching variants between VCFs become easier since different VCFs can have different ALT alleles in them. 

I guess the overall question here is how a locus (in "2. Understanding the VCF format and the haplotype representation") is defined. To me, this is ambigous, and the spec should strive towards an unambigous represtentation. Evaluating each ALT separately does this, but can make haplotypes end up on separate lines in a VCF. 

Thanks! 

Daniel

**Comment by eitanbanks** [comment]
What we decided to do long ago was to *recommend* consistent/unambiguous representation, but not to require it.  Ultimately, genomic variation really can be ambiguous.
So I would support text giving a recommendation in this cases, but not requiring that minimal representation must occur.

**Comment by pd3** [comment]
@eitanbanks +1
