### ISSUE TITLE
Bedv1.0 and autoSQL

### ISSUE THREAD

**Issue by cmatKhan** [samtools/hts-specs#661]
There is a suggestion that custom bed formats be specified in the autoSQL format. This seems like a nice tool, but I have only found the docs describing the autoSQL grammar/format, not the source code for the program which parses the specification into a SQL statement and C struct.

It would be nice to include a link to the autoSQL source code in the footnotes, in addition to the address of the docs.

**Comment by michaelmhoffman** [comment]
I think this goes too far for something that is really just a suggestion anyway.
