### ISSUE TITLE
VCF byte order mark

### ISSUE THREAD

**Issue by d-cameron** [samtools/hts-specs#663]
The VCF specifications does not indicate whether the byte order mark is optional, required, or disallowed.

**Comment by jmarshall** [comment]
One of the active VCF maintainers might comment on what existing implementations do in the presence of a BOM, and what they think the intentions were and what changes if any should be made to the spec.

If one were grasping at tea leaves,<sup>™️</sup> one might read “most software that processes VCF files does not have to be aware of the possible presence of multi-byte UTF-8 characters” (VCF 4.3 §1.2) as implying that BOMs are disallowed.

**Comment by jkbonfield** [comment]
Given Wikipedia states it has zero effect on UTF-8 (obvious given it's strictly byte oriented so word size is irrelevant), and also that [its use is not recommended](https://en.wikipedia.org/wiki/Byte_order_mark#cite_note-4), using it in VCF would seem to come under the "courageous decision" moniker!

We already have a list of non-printing characters we disallow, so this is the natural place to extend that sentence/paragraph with a comment about disallowing the byte order mark too.

**Comment by jmarshall** [comment]
This has been addressed by a9b8801e9ae33a0afcdd29decf21ed7f4863f92c for the 4.4 draft. It remains unspecified in the 4.3 spec.
