### ISSUE TITLE
VCF single breakends refers to unclear "table below"

### ISSUE THREAD

**Issue by cmdcolin** [samtools/hts-specs#667]
![Screenshot from 2022-08-23 10-15-59 (1)](https://user-images.githubusercontent.com/6511937/186209728-000653c5-3beb-46b7-ad6e-1dfd1d71a5b5.png)

I'm not sure if due to latex formatting it's supposed to refer to the table above or if there is missing content (just as a general note: I find the section a bit hard to understand in general! if it had it's own figure, it could be helpful :))

**Comment by cmdcolin** [comment]
could also be helpful to number the table/code descriptions perhaps

**Comment by d-cameron** [comment]
Keeping the changes minimal so the section numbers and figures don't all change for v4.4 and to ensure the timeline for v4.4 doesn't blow out past the Nov GA4GH Connect session
