### ISSUE TITLE
VCF format for structure variant annotation

### ISSUE THREAD

**Issue by phuang7008** [samtools/hts-specs#675]
Hi there,

While creating a VCF file for my structure variants, I found something odd.

In the VCF specification document v4.3, it says "ID values are case sensitive strings and must not contain whitespace, commas or angle brackets."

While on the examples listed on page 17 for structure variants, the document uses \<DEL\>. 
However, the document doesn't state how to use the "angle brackets". Hence here setting ID vs using ID are different.

if I don't use \<DEL\>, instead of the DEL in the ALT field, the vcf-validator will fail the format checking for my structure variants. 

It might be a good idea to add 1 or 2 sentences after the "ID values are case sensitive strings and must not contain whitespace, commas or angle brackets." as angle brackets MUST be used in the ALT field for defined ID.

Please help clarify this to solve my confusion. Many thanks!

Best,

Peter

**Comment by d-cameron** [comment]
While the possible symbolic alternative alleles header definitions are defined in the section 1.4.5, the actual use of these ID strings (and the requirement for angle bracketing ) is defined in section 1.6.1.5 where the ID Strings are actually used in the record. 

Streamlining this is difficult as it would require restructing the document. For SVs in particular, it's further separated where sections 5.3 and 5.4 are dedicated to a more detailed explanation of the various types of structural variants.

**Comment by phuang7008** [comment]
Thank you for quick response.

Yes, cross reference from 1.4.5 to 1.6.1.5 for the usage would definitely helpful.

Peter
