### ISSUE TITLE
cram: Clarify allowed block compression methods for header container

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#677]
This is regarding _CRAM format specification (version 3.0)_ (2022-08-15).

In § 7.1 "CRAM header container", it says that that block compression method is optionally gzipped.

> The first container in a CRAM file contains a textual header in a single block, optionally gzip compressed.

This can be interpreted as the content can either be raw (uncompressed; compression method 0) or gzipped (compression method 1). However, subsequent text says that gzip is the only compression method allowed.

> Only gzip is allowed as compression method for this block.

Does this mean that the raw compression method is not allowed, and the block(s) in the header container must be gzip compressed?

**Comment by jkbonfield** [comment]
It's perhaps ambiguous, but when it says "only gzip is allowed as compression method for this block" it is stating that for compressed blocks it must use gzip.  It doesn't say anything about whether the data must be compressed.  Quite why it says it must use gzip is anybodies guess!  I forget the logic behind that specific limitation.
