### ISSUE TITLE
cram: Clarify whether container blocks can be empty

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#680]
This is regarding _CRAM format specification (version 3.0)_ (2022-08-15).

According to [the htslib implementation](https://github.com/samtools/htslib/blob/4e61c128238f3e7cbb3b1f4e9c0fdb4880aa9a10/cram/cram_io.c#L1580-L1584), container blocks that have an uncompressed size of 0 are assumed to be uncompressed and empty, regardless of its compression method. This behavior is undefined in § 8 "Block structure".

It is an issue when, e.g., the block compression method is set to rANS 4x8, and the compressed data is empty. This would fail decoding since rANS 4x8 data is inherently nonempty (see § 14.4.1 "rANS compressed data structure").

**Comment by jkbonfield** [comment]
By definition an empty block contains no data within it.  The htslib approach of claiming it's uncompressed is just a way of side-stepping any attempts to do clever things, although admittedly it may gloss over illegal data where the data provided doesn't match the meta-data.  (Eg a gzipped block that is zero long is an invalide gzip stream.)

I would *like* to think this is something the specification shouldn't need to explain, other than a hint that empty blocks are permitted, however I see from SAMEA3302751.alt_bwamem_GRCh38DH.20200922.Finnish.simons.cram that this isn't just an empty block, but an illegal empty block!

It claims to be RANS compressed, but isn't a RANS byte stream.  There is a difference between a compressed blocked of data that when uncompressed yields zero bytes (that's still empty, but is valid), vs an empty block claiming to be compressed.  Argh.

Is this just a legacy thing with ancient data, or is the Java code still producing invalid CRAMs?  Checking...

**Comment by jkbonfield** [comment]
Sigh - still there.  Cut from cram_dump, after using `java -jar ~/work/picard-2.26.11.jar SamFormatConverter I=_.bam O=_.cram R=$HREF`

```
        Block 4/36
            Size:         0 comp / 0 uncomp
            Method:       RANS0 (4)
            Content type: EXTERNAL
            Content id:   3
            Keys:         RI 
```

This is a bug!  I'll file it with them, but for practicality sake I guess we need to add an exception to the specification explaining that empty blocks should be skipped without attempting to decode them. :/
