### ISSUE TITLE
VCF4.4: Inquiries about using EVENT in SNV calls and meaning of GT=0 in CNV calls

### ISSUE THREAD

**Issue by maxrossi91** [samtools/hts-specs#687]
Hi,

Thank you very much for the effort in the v4.4 specs. I have some questions/suggestions about the v4.4 specs:
 
1. `EVENT` and `EVENTTYPE` are listed in the specs as Structural Variants only INFO fields. Would it be fine to use them also to link SNV calls made on segmental duplication regions? I.e., we know that one of the four alleles of two high homologous regions have a SNP but we do not now which of the two regions carry the SNP, so we would like to report two events with a tetraploid call on both regions. E.g.,
    ```
    chr1 100 . G A . . EVENT=SameVariantInSegDup GT 0/0/0/1
    chr1 200 . G A . . EVENT=SameVariantInSegDup GT 0/0/0/1
    ```
2. How can we correctly represent a REF copy number call for a region? Which is related to the following question: How should we interpret a `GT=0` in a CNV call? I think there are two possible interpretations, i.e.
   1. `GT=0` refers only the bases listed in the REF column;
   2. `GT=0` on a CNV call would refer to a CopyNumber REF call for the CNV. i.e, for the whole region from `POS + 1` to `END`.
   
    If we use case 1), then to make a REF CN call we would need to add an entry like
    ```
    chr1 100 . G <CNV> . . CN=1.0;SVLEN=200;END=300 GT:CN 1/1:1.0
    ```
     with `GT=1/1` used to represent a normal genotype. While if we use case 2), then this will leat to a specialization of the meaning of `GT=0` depending of the type of `ALT` in the `ALT` column.
 
3. It would be nice to have a summary table for the SV INFO fields, as there is one for the SNV fields, so it will be easier to lookup fields and descriptions for SV entries as well.
4. There are also SV INFO entries whose description has a period at the end, and some doesn't.

CC: @eroller

**Comment by d-cameron** [comment]
Ok, for CNVs we need to be able to specify:
- CNV change + ref CNV (GT=1/?)
- CNV change + CNV change (GT=1/2 or GT=1/1 depending on whether the change is the same)
- ref CNV + ref CNV (GT=?/?)
- ref CNV + unknown CN (GT = ?/?)
- CNV change + unknown CN (GT=?/?)
- Total CN known but ASCN not (GT=?/?)

I don't think VCF GR in it's current form is able to unambiguously express all of the above.

> I think there are two possible interpretation

The first interpretation is problematic when merging records. Take the following example:
chr 100 . G GTTT,<CNV> CN=2,.;SVLEN=100;END=200 GT 0/1 0/2

Clearly in the first ALT/sample with GT 0/2 then REF is literally the G, thus 0/2 also needs to mean literal REF. This means the interpretation needs to be the second. Problem with this is that this is existing SV callers use REF/GT=0 to mean 'this SV is not present'.

Maybe the answer is to disallow symbolic SV ALT alleles from co-existing with non-symbolic alleles in the same single record.

**Comment by eroller** [comment]
If the spec will disallow symbolic SV ALT alleles from co-existing with non-symbolic alleles, then the spec should probably mention that the 0 in the GT when using symbolic SV ALT alleles means "no SV" rather than the exact reference sequence. Small variants may be ignored by SV callers (certainly true for most CNV callers) and so when a haplotype does not have an SV it is not necessarily the exact reference sequence.

**Comment by d-cameron** [comment]
@eroller @maxrossi91 Can you review https://github.com/samtools/hts-specs/pull/688 and verify that it resolves all the issues raised here?

**Comment by maxrossi91** [comment]
> @eroller @maxrossi91 Can you review #688 and verify that it resolves all the issues raised here?

@d-cameron #688 refers to CN and ASCN. Are you planning to address also the `EVENT` and `EVENTTYPE` being listed as Structural Variants only INFO fields issue?

**Comment by maxrossi91** [comment]
> > @eroller @maxrossi91 Can you review #688 and verify that it resolves all the issues raised here?
> 
> @d-cameron #688 refers to CN and ASCN. Are you planning to address also the `EVENT` and `EVENTTYPE` being listed as Structural Variants only INFO fields issue?

Ignore this. I missed the commits f9412ca and 7ab198a that fixed it.
