### ISSUE TITLE
vcf: Define Number value P

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#705]
VCF 4.4 (specifically 008387af8ae39912d7d7a1b03fbd73e26faa2f3f) introduces the new Number value `P` in [§ 1.6.2 "Genotype fields"](https://samtools.github.io/hts-specs/VCFv4.4.pdf#subsubsection.1.6.2) (2023-01-27). Number values are described in [§ 1.4.2 "Information field format"](https://samtools.github.io/hts-specs/VCFv4.4.pdf#subsubsection.1.4.2) but is missing `P`.

**Comment by eroller** [comment]
Would `P` even make sense for INFO column? I think maybe `P` should only be valid for FORMAT fields where a sample has a defined ploidy so it should just be defined in the Genotype section. Some samples may be triploid some may be diploid for the same reference genome. Specifically, `P` is the number of alleles in the FORMAT/GT field. 

On a related note, should this FORMAT field have `Number=P`:
`##FORMAT=<ID=HAP,Number=1,Type=Integer,Description="Unique haplotype identifier">`
and can this be used to link phased haplotypes from multiple records?

**Comment by jmarshall** [comment]
Note that this `P` is used in the current VCFv4.4 specification for the PSL, PSO, and PSQ genotype fields (though these may not yet have seen widespread use), and has been suggested as being appropriate for some of LAA/LAD/LGT (cf #434).

**Comment by d-cameron** [comment]
Added FORMAT P definition to VCF 4.5. No INFO P though as VCF make no assumptions about ploidy outside of GL. Use a . or a fixed number (e.g. Number=2 for diploid) if the ploidy is known.

**Comment by d-cameron** [comment]
TODO: errata 4.4 to change `P` to `.` since it wasn't properly defined.

**Comment by jmarshall** [comment]
…or add the definition of P to the 4.4 spec. Pros and cons on both sides; IMHO it's best for the 4.4 and 4.5.draft specs to say the same thing for PSL/PSO/PSQ.

Possibly also add a reference to this to the errata or changelog sections.

**Comment by d-cameron** [comment]
Let's go with defining Number=P and explicitly listing it as an errata in Section 7.

**Comment by jkbonfield** [comment]
Fixed
