### ISSUE TITLE
sam: Irrelevant test failure in `aux.fail-f1.sam`

### ISSUE THREAD

**Issue by zaeleus** [samtools/hts-specs#722]
[`test/sam/failed/aux.fail-f1.sam`](https://github.com/samtools/hts-specs/blob/144e32acb582b414a281bf9dc06223b43609a489/test/sam/failed/aux.fail-f1.sam) tests for single-precision floating-point limits, but it also fails by having duplicate `F1` tags, which is irrelevant to the test.

**Comment by jmarshall** [comment]
The same problem exists in _aux.pass-f.sam_ too. Addressed by PR #723.
