### ISSUE TITLE
register bgzip in IANA media types?

### ISSUE THREAD

**Issue by vidboda** [samtools/hts-specs#734]
HI,

if you check these issues:

- https://github.com/pallets/werkzeug/issues/2748
- https://github.com/igvteam/igv.js/issues/1654

you would find out that when used in some frameworks such as Flask, bgzipped files are considered as gzip files based here on python [mimetypes](https://docs.python.org/3/library/mimetypes.html), and an unproper header is set.

This can be annoying when using a popular tool such as igv.js as the bgzip file coming from Flask is not correctly handled by the browser.

To summarize, the bgzip file served by Flask (through its own dev server or through a wsgi server, e.g. using mod_wsgi) comes to the web browser with a `'content-encoding': gzip` header, which causes the browser to uncorreclty uncompress the file and igv.js not being able to handle it.

Indeed, bgzip is not listed in IANA  [media types](https://www.iana.org/assignments/media-types/media-types.xhtml).

Shouldn't it be? And then not being considered as regular gzip files anymore?

**Comment by jkbonfield** [comment]
Moved to hts-specs as this isn't an samtools or htslib issue.

**Comment by jmarshall** [comment]
Thanks for the suggestion. These registrations are being considered by TASC, so I have linked to this discussion on TASC's issue. We'll close this issue here, but expect that TASC will refer to this discussion.
