### ISSUE TITLE
is `*` better than `\*`?

### ISSUE THREAD

**Issue by zhitian-wu** [samtools/hts-specs#748]
I think the manual for SAM format is very clear. Only one trivial question.

In page 6 of the file SAMv1.pdf, you used `\*` to denote a single `*` sign. But it is also possible to omit the backslash, as * is the first character in the regular expression (mentioned in page 236 in the latest POSIX standard).

**Comment by jmarshall** [comment]
You are correct that if these REs were [basic REs](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_03), then either `*` or `\*` could be used equivalently. Nonetheless I think `\*` is clearer — if we changed it to use `*|[A-Za-z=.]+` I expect we would get bug reports asking whether we had typoed by omitting a character before the apparent 0-or-more `*` operator.

However §1 specifies that the SAM specification uses [extended REs](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04_03). For EREs, POSIX (in the current Issue 7) says an `<asterisk>` appearing first in the ERE produces undefined results. So in fact plain `*` would be incorrect as we use EREs.
