### ISSUE TITLE
cram: interpretation of "unmapped" flag in a pseudocode seems incorrect

### ISSUE THREAD

**Issue by athos** [samtools/hts-specs#749]
In the CRAM specification, Section 10.6 has the following pseudocode:

```
procedure DecodeRecord
  ...
  if (BF AND 4) != 0 then
    DecodeMappedRead
  else
    DecodeUnmappedRead
  end if
end procedure
```

I think `(BF AND 4) != 0` in the code should be `(BF AND 4) = 0`, as the `0x04` bit of the `BF` flag means "unmapped". Or am I misunderstanding something?

**Comment by jkbonfield** [comment]
On reviewing outstanding issues I noticed I'd completely forgotten about this one.  My apologies.

Thanks for reporting it.  There's now a PR to fix this problem which I'll merge once I've verified the build works (a formality I'm sure).
