### ISSUE TITLE
SVCLAIM: VCF4.4 and backward compatibility with VCF4.3

### ISSUE THREAD

**Issue by tcezard** [samtools/hts-specs#750]
I'm trying to interpret what is valid/invalid VCF 4.4 file to create vcf-validator test file and more specifically if in general a valid VCF 4.3 file can be upgraded to VCF 4.4 (by changing the `##fileformat` header) and still be valid.

I'm looking at interpretation of SVCLAIM at the moment:
So the record
```
1	1100	.	C	<DUP>	100	PASS	CN=4;END=1200;SVLEN=100
```
is valid 4.3 entry but I interpret it as not compatible with 4.4 because the section on SVCLAIM

> DEL/DUP: SVCLAIM **must** be specified and can be be D, J, or DJ. J and DJ claims indicate a breakpoint between the start and end of the DEL/DUP.

Is that correct ?

**Comment by d-cameron** [comment]
> is valid 4.3 entry but I interpret it as not compatible with 4.4 because the section on SVCLAIM

Correct. The record is ambiguous (in both 4.3 and 4.4) because it's unclear whether it's a copy number gain claim and/or a breakpoint claim and 4.4 cleans this up.
