### ISSUE TITLE
cram: Inconsistent descriptions of auxiliary tag types

### ISSUE THREAD

**Issue by athos** [samtools/hts-specs#757]
When I was going through the CRAM spec, I found some seemingly inconsistent descriptions of auxiliary tags with the SAM/BAM spec:

- Section 8.4 in the CRAM spec has a description like the following, but a tag type `F` is not defined in the SAM/BAM spec
  > tag id followed by BAM tag type code (one of A, c, C, s, S, i, I, f, F, Z, H or B, as described in the SAM specification).  ([link](https://github.com/samtools/hts-specs/blob/346a94a9980b0105e926a019b4e62fa1b9e30910/CRAMv3.tex#L866))
- Section 10.5 in the CRAM spec is [missing a description for tag type `A`](https://github.com/samtools/hts-specs/blob/346a94a9980b0105e926a019b4e62fa1b9e30910/CRAMv3.tex#L1549), which is defined in the SAM/BAM spec, while the same section has a statement saying ["... and type is one of the permitted types documented in the SAM/BAM specification"](https://github.com/samtools/hts-specs/blob/346a94a9980b0105e926a019b4e62fa1b9e30910/CRAMv3.tex#L1548)

**Comment by jkbonfield** [comment]
Both of those look like typos or just oversight.  I can confirm the htslib implementation doesn't use tag type `F` and that `A` is support.

Thanks for reporting this.
