### ISSUE TITLE
0-based coordinate system error in sam spec?

### ISSUE THREAD

**Issue by jacobscgc** [samtools/hts-specs#786]
Hi, 

I might be missing something, but it seems that in the sam spec (SAMv1.pdf) on page 2 in the section describing the 0-based coordinate system, there is an error. The example describing the 1-based and 0-based coordinate system take base 3-7 (below in bold).
Which would give:

| | | | | | | | | Notation |
|-|-|-|-|-|-|-|-|-|
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | [ 2, 6 ) |
| A | T | **G** | **C** | **A** | **A** | **C** | G
| 1 | 2 |  3 | 4 | 5 | 6 | 7 | 8 | [ 3, 7 ] |

The example given for the 0-based notation states however [ 2, 7 )
Which seems incorrect to me. At least as I understand it, it would not describe the same bases as [ 3, 7 ] would in the 1-based system.

Is it that in the 0-based coordinate system, the first digit is included but the second is not? So, in that case, [2, 7) would mean bases 2-6?
Or is this indeed a mistake in the docs?

Thanks,
Chris

**Comment by jmarshall** [comment]
There is no error here.

What the spec says for 0-based is: “in this coordinate system, a region is specified by a half-closed-half-open interval”. (Admittedly, it assumes the reader understands what it means by this. But the spec is not intended to be an introduction to bioinformatics.) You should also pay attention to the [use of `[` and `)` in this notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints).

There are two coordinate systems commonly used in bioinformatics: one-based inclusive like [3,7], which is familiar to humans, and zero-based half-open like [2,7), which is convenient for arithmetic (this excludes the base numbered 7, which is the 8th in human reckoning).

There are eight possible coordinate systems that could be generated by combining zero vs. one based, inclusion/exclusion of the lower bound, inclusion/exclusion of the upper bound. But these two are the common ones, and using any of the other six would lead only to confusion.

**Comment by jacobscgc** [comment]
Alright thanks for the clarification John. 
I was confused by the use of 'inclusive' in the description, but that refers to the bases included, not to the notation itself. 
I'll double check next time before asking it here.
