### ISSUE TITLE
[Improvement] BAM file format, optional strandedness field in header for RNA-seq 

### ISSUE THREAD

**Issue by rLannes** [samtools/hts-specs#787]
Hi,

I believe having the opportunity to set up a flag in the BAM file header to specify the strandedness of the RNA-seq data would improve the data pipeline, the integration with other tools, and diminish the likelihood of mistakes. I understand there is already a description tag for custom strings, but in my opinion, this is not as suitable as having a specific tag that can be consistently checked by any software or user.

Having to specify it at each subsequent step of analysis increases the chance of an error occurring. For example, when counting the number of reads mapping to genomic features or trying to visualize the read coverage.

Even IGV (a broadly used BAM file visualization software) does not properly handle stranded RNA-seq, which is, for me, a dramatic indication of how such valuable information is currently discarded.

It will also simplify data management, with the information embedded in the BAM file.

In the end, I do believe that having a specific flag for strandedness of the data that could be set by the end user would be a good start for better supporting this technology.

This is my first time contributing here. I quickly went through the issues and could not find anything related to this.

Best regards,
Romain

**Comment by jkbonfield** [comment]
I'm not familier with the nature of the data.  I assume this is the whole library coming from the same strand, rather than each individual template being a single strand?  The reason for this assumption is that the former could be specified in a header while the latter in a record specific aux tag.

It sounds like something that could be added to the library fields linked to in the read-group.  Really the header is too restrictive while still being somewhat arbitrary, making it hard to edit.   Eg program (PG) is a top-level identifier, but sequencing platform or library are not.   It'd be nice for example to have a library object with meta-data, but adding say an `@LB` field would break huge numbers of bits of code!

So at best all we could hope for would be an addition key:value pairing on the RG field to indicate library strand.  Or to replicate data in the BAM records via aux tags, which may still be preferable when dealing with mixed data sets as it's one level less of indirection and the data is small (essentially just 1 or 2 bits of information).  See https://github.com/samtools/hts-specs/issues/276 for an example.  Is this the same issue you are tackling?

Do you have a more concrete proposal, even if it's just example text of what you think the header should look like?

**Comment by rLannes** [comment]
Thank you for your detailed answer,

First, I would like to clarify what I mean by strandedness: 
    Stranded RNA-seq is a library preparation that allows one to determine from which strand each read/fragment comes. Inside the BAM file, both + and - strands are present. The library prep can be of three types: Unstranded, FR (if read1 is forward and read2 is reverse, it is + strand; - strand for the opposite), or RF (if read2 is forward and read1 is reverse, it is + strand; - strand for the opposite). To determine the strandedness of a read/fragment, one needs to know the library type (FR or RF) and use the read's flag to determine the read's orientation. For example, in the case of an RF library, a read is + strand if it is either: 128+ and 16- OR 64+ and 32-. (second in pair + and read reverse strand - OR first in pair + and mate reverse strand -)

The TS tag is used in the case of pseudo-aligners that try to infer the sense of the transcript. (I was not aware of this, as I have never used such tools.).

Here, the library-type information is required to infer the strand of each read along with the read's flag. From what I understand, you suggest using an RG tag to specify if the read comes from an FR, RF, or unstranded library, right? Does that mean all reads from the same library would share the same tag? (which is what we want!)

What I am trying to achieve is a tag that any software could check to know the library strandedness type in order to act accordingly, and that would store the information (simplifying the data management). The RG tag seems like a good idea. All reads from the same library should share the same tag. I was thinking of a tag that, if set, would take a defined value such as FR, RF, or UN (could be extended in the future).

Best regards,
Romain

**Comment by jkbonfield** [comment]
Thanks for clarifying.

So yes, if we were designing this from scratch, it would be an attribute associated with the library (which in turn is associated with a read-group).  However adding new things to the spec always risks compatibility problems with existing software, even though in theory they should be designed with future extensions in mind. 

Would simply using the TS field be sufficient for your needs?  It feels to me like from a programmatic point of view it's a logically easy process to handle.  Some libraries would have all reads the same while others would have reads with inferred strand post alignment, but this difference can be hidden away via a single mechanism to get the strand for any individual read.  It's perhaps not still ideal,  but easy to do (ie it already exists).

**Comment by rLannes** [comment]
Thank you again for your time and your answer. The reality of software development is catching up. For me, the current status is as good as using the TS tag (meaning no change is required). The code I write is mainly used internally, so I don't feel the need to ask for changes that could break the API. I've opened an issue on the IGV page to get their input on this. As one of the most widely used software for BAM file visualization, I believe it could be relevant to have their perspective.

**Comment by jrobinso** [comment]
Knowing if the library is RF, FR, or unpairing is useful generally, not just for determining transcript strand.  IGV infers this information from the reads itself but an explicit declaration would be much preferred.  However I wouldn't call that "strand type" it just happens to be information from which you can combine with other information to derive a transcript strand.   This seems needlessly complex for that purpose however when an explicit tag exists.

IGV has recognized an "XS" strand as indicating transcript strand for a very long time.   I was unaware of the "TS" tag which I assume replaced the "XS" convention.   I will update IGV to use either.

**Comment by rLannes** [comment]
I am closing this issue, but thank you for your time and consideration. It was great to exchange with you.

Best regards, 
romain

**Comment by jkbonfield** [comment]
I had totally managed to forget about the explicit statement in the SAM spec about lowercase tags being valid KEY:value fields in the headers.  Not the headers themselves (fixed PG, SQ, TG, etc) but the aux part of them.  They turned up in dd2b32ef all the way back in 2010.

So while it's not official, which is preferable, it would mean that you can experiment with the usefulness of such annotations locally without the risk of knowingly breaking any downstream tools.  From a spec maintainer stance, we should ideally be led by tested implementations with support from multiple sources (as was the case with the per-record XS tag and turning it into an official TS tag).
