### ISSUE TITLE
Clarify SVCLAIM for deletion bridges

### ISSUE THREAD

**Issue by ctsa** [samtools/hts-specs#789]
Using the VCF 4.4 definition of `SVCLAIM`, could it be clarified whether a 'deletion bridge' detected from both read depth and matched breakends at each copy number boundary would be `SVCLAIM=DJ` or just `SVCLAIM=D`? My reading of the spec leans toward the latter but would be good to know if this is the intent.

By deletion bridge, I mean that the breakends at the copy number boundaries of this deletion do not directly connect to each other, e.g. Fig 2a @ https://doi.org/10.1016/j.cell.2013.03.021

cc: @d-cameron / @cwhelan

**Comment by d-cameron** [comment]
SVCLAIM is purely to disambiguate breakpoint <DEL> calls from copy number
<DEL> calls.
If you can write the <DEL> in BND notation without changing the meaning of
the record then it's SVCLAIM=J
If you can write the <DEL> as a <CNV> record without changing the meaning
of the record then it's SVCLAIM=D
If you're making a claim about both the presence of the breakpoint and the
lower copy number in the internal segment, then it's SVCLAIM=DJ

If you have more complex events such as "deletion bridges" or "synthetic
deletions" (e.g. FigS1 @ https://doi.org/10.1016/j.xgen.2022.100112) then
they should be represented with their constituent breakpoints and copy
number segments and linked together with EVENT & EVENTTYPE. The only
multi-breakpoint event that can be represented in a single symbolic allele
in VCF is a perfect inversion with 0 bases duplicated or lost on either
side of the inversion. At present, there are no plans to expand the list of
symbolic structural variant alleles.

Note that EVENTTYPE is intentionally an underdefined open vocabulary.
There's currently no consensus as to how to classify complex SVs (e.g. Sequence
Ontology, PCAWG, LINX, gnomAD-SV all have different classification schemes)
so both DEL:BRIDGE and DEL:SYNTHETIC are valid.


> I mean that the breakends at the copy number boundaries of this deletion
do not directly connect to each other

For complex rearrangements such as chromothripsis, you'll find that as the
events get more complex, breakpoint orientations tends to equal ++/--/+-/-+
oriented breakpoints so only 1/4 of the complex "deletion bridge"
breakpoint are even in deletion-like orientation thus can't even be
represented with a VCF <DEL> record at all. You end up with events that
look like
https://github.com/hartwigmedical/hmftools/blob/master/linx/docs/small2.png
. Lots of <DEL> SVCLAIM=D segments connected together by breakpoints in all
4 orientations (my personal preference is to use BND notation, but
representing the deletion-like breakpoints using <DEL> SVCLAIM=J syntax has
identical semantics).

**Comment by ctsa** [comment]
Thanks for the very thorough clarification Daniel!

It might help to clarify best practice in the spec by showing an example of how this would all come together for a simple synthetic deletion example.

Here's an image I put together of what such an example could look like:

<img src="https://github.com/user-attachments/assets/17848393-0ed8-4675-8c9b-86bd7b6b024d" alt="synthetic deletion example" width="800"/>

If I understand your comments above, one possible spec VCF representation of such an event is:

```
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  SAMPLE
chrA    100 del_1   N   <DEL>   .   .   EVENT=SD1;SVCLAIM=D GT:CN  0/1:1
chrA    100 bnd_1   N   N]chrB:350] .   .   EVENT=SD1   GT  0/1
chrA    201 bnd_2   N   [chrB:301[N .   .   EVENT=SD1   GT  0/1
chrB    300 dup_1   N   <DUP>   .   .   EVENT=SD1;SVCLAIM=D GT:CN  .:3
chrB    301 bnd_3   N   [chrA:201[N .   .   EVENT=SD1   GT  0/1
chrB    350 bnd_4   N   N]chrA:100] .   .   EVENT=SD1   GT  0/1
```

Is this on the right track?

**Comment by d-cameron** [comment]
>Is this on the right track?

You are indeed on the right track. I would also add the following annotation:
- EVENTTYPE annotation if you have a classifier (e.g. LINX, JaBbA)
- FORMAT PSL:PSO phasing information to the two breakpoints to make it explicit that they are cis-phased and adjacent in a single derivate chromosome. Missing these, this event could also be a balanced interchromsomal rearrangement with a small dep & del at the rearrangement breakpoint.

**Comment by d-cameron** [comment]
If you want to get pedantically technical then you could use INFO CN to define ASCN for the segments and phase a specific copy of each CN segment with the breakpoints (e.g. you have informative, phased SNVs within the CN segments).

It should be noted that the EVENT model is a simple model so there are some limitations. The two main ones that come to mind are the inability to associate a single CN segment with multiple EVENTs, and the inability to annotate a REF call with an EVENT (since NUMBER=A).

**Comment by ctsa** [comment]
Lots of additional good points here for representing more complex SVs in VCF 4.4. Since you've clarified the original `SVCLAIM` question I'll go ahead and close this issue as answered. Thanks for your help!
