### ISSUE TITLE
Request for clarification in spec regarding Meta-information lines

### ISSUE THREAD

**Issue by abaumann** [samtools/hts-specs#79]
I think the spec is unclear/potentially misleading regarding meta-information lines, which the spec says "must be key=value pairs".  This is in response to the question at https://github.com/samtools/htsjdk/issues/43.
Parsers handling these lines as strict key=value pairs will lose information from identical keys.  The `INFO`, `FILTER`, and `FORMAT` keys are special cases in which additional key information is actually contained in the value <ID=...>.  Similar examples show up in the spec for `##ALT` and `##contig` that utilize the `<ID=...>` form.  

I think the spec should either:
* specify that using `<ID=...>` in the value can be used as part of the key so parsers could make that assumption and avoid loss of information (some parsers may already, but it's not explicit in the spec)
* clarify that any non-unique key that is not `INFO`, `FILTER` or `FORMAT` may be lost by parsers that treat these as key=value pairs
* allow the key to include the ID instead of using the value to include additional key information

The use of key information within the value (`<ID=...>`) I find very strange and inconsistent.  I'd more expect something in the form `INFO<ID=NS>=<Number=1, Type=...>` given that the spec says these are key=value pairs.  

Clearly changing the spec can lead to issues in parsers that expect the existing form, so clarifications within the spec may be the best option.

**Comment by pd3** [comment]
In the VCFv4.3 draft there is a sentence about this in section 1.2: "their ID must be unique within their type".
