### ISSUE TITLE
odd/bad SV in spec example.

### ISSUE THREAD

**Issue by brentp** [samtools/hts-specs#84]
The 4.2 and 4.3 specs have this as the first example SV:
```
1 2827694 rs2376870   CGTGGATGCGGGGAC C   .   PASS    SVTYPE=DEL;END=2827762;HOMLEN=1;HOMSEQ=G;SVLEN=-68  GT:GQ   1/1:13.9
```

If this is correct due to something about micro-homology, it needs more explanation. END jives with SVLEN, but why is the REF shorter than 68 bases?

**Comment by pd3** [comment]
Hi, I've consulted this with others and we think it is a bug. Most likely it was introduced when the specification was converted to pdf - the line was too long and did not fit on the page. If there are no objections, I'll change the example to read SVLEN=-14 and END=2827708.

**Comment by jmarshall** [comment]
Indeed.  The relevant line in the [1000genomes wiki version](http://www.1000genomes.org/wiki/analysis/variant-call-format/vcf-variant-call-format-version-42) — on the previous revision of that page, which unfortunately you have to be logged in to see — was

    1 2827694   rs2376870  CGTGGATGCGGGGACCCGCATCCCCTCTCCCTTCACAGCTGAGTGACCCACATCCCCTCTCCCCTCGCA  C . PASS  SVTYPE=DEL;END=2827762;BKPTID=Pindel_LCS_D1099159;HOMLEN=1;HOMSEQ=G;SVLEN=-68 GT:GQ 1/1:13.9

so BKPTID was removed and REF was abbreviated.  (The other records are unchanged apart from the removal of boring IMPRECISE and MEINFO tags.)

**Comment by arq5x** [comment]
Thanks for addressing this, all.
