### ISSUE TITLE
Real-world usage of 0x200 failedVendorQualityChecks flag

### ISSUE THREAD

**Issue by jmarshall** [samtools/hts-specs#85]
The SAM specification describes the 0x200 flag bit as _not passing quality controls_ (and the pre-LaTeX version of the spec described it as _the read fails platform/vendor quality checks_).

It also describes it as the _filtered_ bit in §2 (Recommended Practices) when introducing annotation dummy reads:

> Annotation dummy reads: These have SEQ set to `*`, FLAG bits 0x100 and 0x200 set (secondary and filtered), and a CT tag.

In the real world today, do we actually see bad-quality reads in BAM files with their _not passing quality controls_ flags set?

@lh3 [recently commented elsewhere](https://github.com/ga4gh/schemas/pull/292#issuecomment-97127759) that "almost no one uses failedVendorQualityChecks nowadays".  Probably the usual practice is for such quality-failed reads to be just omitted from BAM files rather than kept and marked with this flag, and probably this has been the case for quite some time.

Would it be worth repurposing this flag as a general _this-read-is-filtered-out_ flag?  This would be as simple as changing the description in the flag bit table, e.g.:

> not passing filters, such as platform/vendor quality controls

**Comment by lh3** [comment]
I support this.

**Comment by yfarjoun** [comment]
With hiseqX this is true since there are so many failed reads, but with the
non-patterned flowcell machines we keep the failing reads around. I
remember that David Jaffee said that his group looks at all reads,
including the PF failed reads for assembly....

**Comment by lh3** [comment]
John just changed this flag to something more general. It would not cause any compatible issues as far as I see. Broad can still use this flag to mark PF'ed reads.

**Comment by nh13** [comment]
I support this as well.

**Comment by yfarjoun** [comment]
Hi,

I might be missing something but I couldn't find 0x800 bit definition from
the BAM spec in the v3 spec document for CRAM.

The flag is included in the code
(htsjdk/samtools/cram/structure/CramCompressionRecord.java:41), but not in
the document.

I presume that this is a typo, but I just wanted to make sure before
changing the document.

Yossi.

**Comment by jmarshall** [comment]
@yfarjoun: This is #61, and I'm a bit surprised they still haven't made this seemingly obvious editorial fix…

**Comment by yfarjoun** [comment]
sorry, I should have checked the issues.

Y.
