### ISSUE TITLE
GLE field is ill-defined

### ISSUE THREAD

**Issue by pd3** [samtools/hts-specs#90]
The example provided in the specification is `0:-75.22,1:-223.42,0/0:-323.03,1/0:-99.29,1/1:-802.53`, however, the colon cannot be used as a separator.

Proposed solution: use a different separator instead, a semicolon `;` or maybe better the equality sign `=`, so that the example becomes `0=-75.22,1=-223.42,0/0=-323.03,1/0=-99.29,1/1=-802.53`

**Comment by bhandsaker** [comment]
Is anyone using the GLE tag?
There have been a couple of discussions offline suggesting that nobody is aware of any software that is currently using the GLE tag.
If indeed it is not being used, perhaps we could just remove it from the spec (lighter is better).
