### ISSUE TITLE
Request for comments: should PEDIGREE VCF header lines be required to have an ID field?

### ISSUE THREAD

**Issue by droazen** [samtools/hts-specs#96]
The proposed VCF 4.3 spec (https://github.com/samtools/hts-specs/pull/88) mandates that "All structured lines that have their value enclosed within ”<>” require an ID which must be unique within their type." This new requirement necessitates a change to ##PEDIGREE header lines, which now require an ID. Eg., 
        
        ##PEDIGREE=<ID=PedigreeID,Name_0=G0-ID,Name_1=G1-ID,...,Name_N=GN-ID>).

Since this breaks backwards compatibility for the sake of consistency within the spec, are there any objections to making this change?

**Comment by abecasis** [comment]
I think we may be able to accomplish the change in a way that is backward compatible (or at least more so).

Specifically, we could change the pedigree tag to look like this:

a) To indicate clonal relationship (e.g. between tumor and germline sample)

##PEDIGREE=<ID=TumorSampleID,Original=GermlineID> 

[or, to specify two samples derived from same germline]

##PEDIGREE=<ID=TumourSample,Original=GermlineID>
##PEDIGREE=<ID=SomaticNonTumour,Original=GermlineID>

b) To specify a family relationship for diploids, like humans:

##PEDIGREE=<ID=ChildID,Father=FatherID,Mother=MotherID>

c) And in the arbitrary case,would become:

##PEDIGREE=<ID=SampleID,Name_1=Ancestor_1,...,Name_N=Ancestor_N>

We should be able to describe any relationship and should probably make clear that, to fully specify the pedigree, the VCF can define relationships between IDs that are not present in the VCF (but are ancestors of others that are).

Goncalo

**Comment by pd3** [comment]
@abecasis I like this, +1 from me

**Comment by pd3** [comment]
As there were no other comments, I made the change and will close the issue now.
Thanks

**Comment by heuermh** [comment]
Sorry to comment on an old closed issue.

From my reading of the specification, the pedigree meta lines record "relationships between genomes", and as there is "a distinction between sample and genome" supported by the sample meta line, I understood the IDs used in pedigree meta lines to refer to Genomes:
```
##SAMPLE=<ID=Blood,Genomes=Germline,Mixture=1.,Description="Patient germline genome">
##SAMPLE=<ID=TissueSample,Genomes=Germline;Tumor,Mixture=.3;.7,Description="Patient germline genome;Patient tumor genome">
```
I.e. `Germline` and `Tumor` above.

This change still refers to genomes in the text but the examples appear to be using sample IDs instead, `Blood` and `TissueSample` above.

Plus, if "the VCF can define relationships between IDs that are not present in the VCF" that should be mentioned in the specification.
